/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId The product ID of the addon product.
 * @param minQuantity Minimum quantity of the addon allowed to be purchased.
 * @param isSeatAddon Flag indicating if this addon represents a seat/license limit increment.
 * @param maxQuantity Maximum quantity of the addon allowed to be purchased (optional).
 * @param priceOverride Price override for the addon product when purchased with this parent (optional).
 */


data class AddonCreate (

    /* The product ID of the addon product. */
    @Json(name = "productId")
    val productId: kotlin.String,

    /* Minimum quantity of the addon allowed to be purchased. */
    @Json(name = "minQuantity")
    val minQuantity: java.math.BigDecimal = java.math.BigDecimal("0"),

    /* Flag indicating if this addon represents a seat/license limit increment. */
    @Json(name = "isSeatAddon")
    val isSeatAddon: kotlin.Boolean = false,

    /* Maximum quantity of the addon allowed to be purchased (optional). */
    @Json(name = "maxQuantity")
    val maxQuantity: java.math.BigDecimal? = null,

    /* Price override for the addon product when purchased with this parent (optional). */
    @Json(name = "priceOverride")
    val priceOverride: java.math.BigDecimal? = null

) {


}

