/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param prefix 
 * @param status 
 * @param allowWrite 
 * @param expiresAt 
 * @param createdAt 
 * @param apiKey The raw API key. Only returned once during creation.
 * @param lastUsedAt 
 */


data class ApiKeyResponseDto (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "prefix")
    val prefix: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "allowWrite")
    val allowWrite: kotlin.Boolean,

    @Json(name = "expiresAt")
    val expiresAt: java.time.OffsetDateTime,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* The raw API key. Only returned once during creation. */
    @Json(name = "apiKey")
    val apiKey: kotlin.String? = null,

    @Json(name = "lastUsedAt")
    val lastUsedAt: kotlin.Any? = null

) {


}

