/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Name of the brand
 * @param websiteUrl The website URL associated with the brand
 * @param supportEmail Support email address for customer service
 * @param description Short description of the brand
 * @param logoUrl Brand logo image URL
 * @param statementDescriptor Credit card statement descriptor (Max 22 chars)
 */


data class BrandUpdate (

    /* Name of the brand */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The website URL associated with the brand */
    @Json(name = "websiteUrl")
    val websiteUrl: kotlin.String? = null,

    /* Support email address for customer service */
    @Json(name = "supportEmail")
    val supportEmail: kotlin.String? = null,

    /* Short description of the brand */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Brand logo image URL */
    @Json(name = "logoUrl")
    val logoUrl: kotlin.String? = null,

    /* Credit card statement descriptor (Max 22 chars) */
    @Json(name = "statementDescriptor")
    val statementDescriptor: kotlin.String? = null

) {


}

