/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The unique business ID
 * @param title Title or name of the business
 * @param whopId The Whop Company ID
 * @param merchantId The merchant owner ID
 * @param verified Whether the business has been KYC-verified on Whop
 * @param sendCustomerEmails Whether auto-emails are enabled for customers
 * @param memberCount Total members/customers under this business
 * @param defaultCurrency The default currency of the business
 * @param publishedReviewsCount Number of published user reviews on Whop
 * @param createdAt Timestamp when the business record was created
 * @param updatedAt Timestamp when the business record was last updated
 * @param description A description explaining what the business does
 * @param route Whop friendly URL path route
 * @param metadata Custom key-value metadata
 * @param targetAudience The target audience description
 * @param socialLinks Social links setup
 * @param affiliateInstructions Markdown instructions for affiliates
 * @param whopCreatedAt Whop account creation timestamp
 * @param whopUpdatedAt Whop account last updated timestamp
 * @param logoUrl Brand logo image URL resolved from primary brand
 */


data class Business (

    /* The unique business ID */
    @Json(name = "id")
    val id: kotlin.String,

    /* Title or name of the business */
    @Json(name = "title")
    val title: kotlin.String,

    /* The Whop Company ID */
    @Json(name = "whopId")
    val whopId: kotlin.String,

    /* The merchant owner ID */
    @Json(name = "merchantId")
    val merchantId: kotlin.String,

    /* Whether the business has been KYC-verified on Whop */
    @Json(name = "verified")
    val verified: kotlin.Boolean,

    /* Whether auto-emails are enabled for customers */
    @Json(name = "sendCustomerEmails")
    val sendCustomerEmails: kotlin.Boolean,

    /* Total members/customers under this business */
    @Json(name = "memberCount")
    val memberCount: java.math.BigDecimal,

    /* The default currency of the business */
    @Json(name = "defaultCurrency")
    val defaultCurrency: kotlin.String,

    /* Number of published user reviews on Whop */
    @Json(name = "publishedReviewsCount")
    val publishedReviewsCount: java.math.BigDecimal,

    /* Timestamp when the business record was created */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Timestamp when the business record was last updated */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* A description explaining what the business does */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Whop friendly URL path route */
    @Json(name = "route")
    val route: kotlin.String? = null,

    /* Custom key-value metadata */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null,

    /* The target audience description */
    @Json(name = "targetAudience")
    val targetAudience: kotlin.String? = null,

    /* Social links setup */
    @Json(name = "socialLinks")
    val socialLinks: kotlin.Any? = null,

    /* Markdown instructions for affiliates */
    @Json(name = "affiliateInstructions")
    val affiliateInstructions: kotlin.String? = null,

    /* Whop account creation timestamp */
    @Json(name = "whopCreatedAt")
    val whopCreatedAt: java.time.OffsetDateTime? = null,

    /* Whop account last updated timestamp */
    @Json(name = "whopUpdatedAt")
    val whopUpdatedAt: java.time.OffsetDateTime? = null,

    /* Brand logo image URL resolved from primary brand */
    @Json(name = "logoUrl")
    val logoUrl: kotlin.String? = null

) {


}

