/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The checkout link ID
 * @param quantity Quantity to purchase
 * @param showDiscounts Whether to show discounts on the checkout page
 * @param createdAt Timestamp when the link was created
 * @param updatedAt Timestamp when the link was last updated
 * @param title The title of the checkout link
 * @param productId The linked Product ID
 * @param collectionId The linked Collection ID
 * @param customerName Pre-filled customer name
 * @param customerEmail Pre-filled customer email
 * @param addressLine1 Pre-filled address line 1
 * @param city Pre-filled city
 * @param state Pre-filled state
 * @param postalCode Pre-filled postal code
 * @param country Pre-filled country
 * @param redirectUrl URL to redirect to after successful payment
 * @param cancelUrl URL to redirect to if payment is cancelled
 */


data class CheckoutLinkResponseDto (

    /* The checkout link ID */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Quantity to purchase */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,

    /* Whether to show discounts on the checkout page */
    @Json(name = "showDiscounts")
    val showDiscounts: kotlin.Boolean,

    /* Timestamp when the link was created */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Timestamp when the link was last updated */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* The title of the checkout link */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* The linked Product ID */
    @Json(name = "productId")
    val productId: kotlin.String? = null,

    /* The linked Collection ID */
    @Json(name = "collectionId")
    val collectionId: kotlin.String? = null,

    /* Pre-filled customer name */
    @Json(name = "customerName")
    val customerName: kotlin.String? = null,

    /* Pre-filled customer email */
    @Json(name = "customerEmail")
    val customerEmail: kotlin.String? = null,

    /* Pre-filled address line 1 */
    @Json(name = "addressLine1")
    val addressLine1: kotlin.String? = null,

    /* Pre-filled city */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* Pre-filled state */
    @Json(name = "state")
    val state: kotlin.String? = null,

    /* Pre-filled postal code */
    @Json(name = "postalCode")
    val postalCode: kotlin.String? = null,

    /* Pre-filled country */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* URL to redirect to after successful payment */
    @Json(name = "redirectUrl")
    val redirectUrl: kotlin.String? = null,

    /* URL to redirect to if payment is cancelled */
    @Json(name = "cancelUrl")
    val cancelUrl: kotlin.String? = null

) {


}

