/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The public product identifier (whopId or internal ID)
 * @param quantity Quantity of this product in the collection
 */


data class CollectionProductRefDto (

    /* The public product identifier (whopId or internal ID) */
    @Json(name = "id")
    val id: kotlin.String,

    /* Quantity of this product in the collection */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal

) {


}

