/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The unique identifier (ID) of the product.
 * @param name The display name of the product.
 * @param price The price amount of the product (e.g. 29.00).
 * @param currency The three-letter ISO currency code (e.g. USD, VND, EUR).
 * @param status The lifecycle status of the product (e.g. ACTIVE, ARCHIVED).
 * @param imageUrl URL of the product cover image.
 * @param taxCategory The tax classification for the product.
 * @param pricingType Pricing model of the product.
 * @param discount Discount value as a percentage or fixed amount.
 * @param hasLicenseKey Indicates if the product issues a cryptographically secure software license key upon checkout completion.
 * @param hasDigitalDelivery Whether the product includes digital file downloads upon purchase.
 * @param hasGithubAccess Whether the product includes GitHub repository access.
 * @param githubRepo GitHub repository to grant access to (format: owner/repo).
 * @param githubPermission GitHub collaborator permission level.
 * @param isTaxInclusive Whether the product price already includes applicable sales taxes.
 * @param billingPeriod The subscription billing cycle interval in days (for subscription products).
 * @param trialPeriodDays Trial duration in days for subscription products.
 * @param expirationDays Automatic expiration period in days for the subscription entitlement.
 * @param statementDescriptor Custom text displayed on customer credit card statements for purchases of this product.
 * @param payWhatYouWant Indicates if customers are allowed to enter a custom pricing amount at checkout.
 * @param metadata Custom developer metadata key-value pairs associated with the product.
 * @param customFields Custom form field questions to ask the customer during checkout.
 * @param stock Available stock quantity, or null for unlimited inventory.
 * @param activationLimit Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true).
 * @param isListed Defines if the product is listed publicly on the merchant's storefront template.
 * @param isFree Whether the product is free.
 * @param createdAt Timestamp indicating exactly when the product was created.
 * @param updatedAt Timestamp indicating when the product was last modified.
 * @param isPermanentlyDeleted Indicates if the product has been permanently deleted.
 * @param brandId Optional brand identifier.
 * @param digitalLink Secure link for digital delivery.
 * @param instructions Special instructions provided upon purchase.
 * @param activationMessage Custom message displayed when a license key is activated.
 * @param expiryHours Number of hours until the license key expires.
 * @param businessId The unique identifier of the business owning this product.
 * @param quantity Quantity of the product in the collection
 * @param description A comprehensive rich text description of the product.
 */


data class CollectionProductDto (

    /* The unique identifier (ID) of the product. */
    @Json(name = "id")
    val id: java.util.UUID,

    /* The display name of the product. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The price amount of the product (e.g. 29.00). */
    @Json(name = "price")
    val price: java.math.BigDecimal,

    /* The three-letter ISO currency code (e.g. USD, VND, EUR). */
    @Json(name = "currency")
    val currency: kotlin.String,

    /* The lifecycle status of the product (e.g. ACTIVE, ARCHIVED). */
    @Json(name = "status")
    val status: kotlin.String,

    /* URL of the product cover image. */
    @Json(name = "imageUrl")
    val imageUrl: kotlin.String?,

    /* The tax classification for the product. */
    @Json(name = "taxCategory")
    val taxCategory: CollectionProductDto.TaxCategory,

    /* Pricing model of the product. */
    @Json(name = "pricingType")
    val pricingType: CollectionProductDto.PricingType,

    /* Discount value as a percentage or fixed amount. */
    @Json(name = "discount")
    val discount: java.math.BigDecimal?,

    /* Indicates if the product issues a cryptographically secure software license key upon checkout completion. */
    @Json(name = "hasLicenseKey")
    val hasLicenseKey: kotlin.Boolean,

    /* Whether the product includes digital file downloads upon purchase. */
    @Json(name = "hasDigitalDelivery")
    val hasDigitalDelivery: kotlin.Boolean,

    /* Whether the product includes GitHub repository access. */
    @Json(name = "hasGithubAccess")
    val hasGithubAccess: kotlin.Boolean,

    /* GitHub repository to grant access to (format: owner/repo). */
    @Json(name = "githubRepo")
    val githubRepo: kotlin.String?,

    /* GitHub collaborator permission level. */
    @Json(name = "githubPermission")
    val githubPermission: CollectionProductDto.GithubPermission?,

    /* Whether the product price already includes applicable sales taxes. */
    @Json(name = "isTaxInclusive")
    val isTaxInclusive: kotlin.Boolean,

    /* The subscription billing cycle interval in days (for subscription products). */
    @Json(name = "billingPeriod")
    val billingPeriod: kotlin.Int?,

    /* Trial duration in days for subscription products. */
    @Json(name = "trialPeriodDays")
    val trialPeriodDays: kotlin.Int?,

    /* Automatic expiration period in days for the subscription entitlement. */
    @Json(name = "expirationDays")
    val expirationDays: kotlin.Int?,

    /* Custom text displayed on customer credit card statements for purchases of this product. */
    @Json(name = "statementDescriptor")
    val statementDescriptor: kotlin.String?,

    /* Indicates if customers are allowed to enter a custom pricing amount at checkout. */
    @Json(name = "payWhatYouWant")
    val payWhatYouWant: kotlin.Boolean,

    /* Custom developer metadata key-value pairs associated with the product. */
    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>?,

    /* Custom form field questions to ask the customer during checkout. */
    @Json(name = "customFields")
    val customFields: kotlin.collections.List<kotlin.Any>?,

    /* Available stock quantity, or null for unlimited inventory. */
    @Json(name = "stock")
    val stock: kotlin.Int?,

    /* Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true). */
    @Json(name = "activationLimit")
    val activationLimit: kotlin.Int,

    /* Defines if the product is listed publicly on the merchant's storefront template. */
    @Json(name = "isListed")
    val isListed: kotlin.Boolean,

    /* Whether the product is free. */
    @Json(name = "isFree")
    val isFree: kotlin.Boolean,

    /* Timestamp indicating exactly when the product was created. */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Timestamp indicating when the product was last modified. */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Indicates if the product has been permanently deleted. */
    @Json(name = "isPermanentlyDeleted")
    val isPermanentlyDeleted: kotlin.Boolean,

    /* Optional brand identifier. */
    @Json(name = "brandId")
    val brandId: kotlin.String?,

    /* Secure link for digital delivery. */
    @Json(name = "digitalLink")
    val digitalLink: kotlin.String?,

    /* Special instructions provided upon purchase. */
    @Json(name = "instructions")
    val instructions: kotlin.String?,

    /* Custom message displayed when a license key is activated. */
    @Json(name = "activationMessage")
    val activationMessage: kotlin.String?,

    /* Number of hours until the license key expires. */
    @Json(name = "expiryHours")
    val expiryHours: kotlin.Int?,

    /* The unique identifier of the business owning this product. */
    @Json(name = "businessId")
    val businessId: kotlin.String,

    /* Quantity of the product in the collection */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal,

    /* A comprehensive rich text description of the product. */
    @Json(name = "description")
    val description: kotlin.String? = null

) {

    /**
     * The tax classification for the product.
     *
     * Values: digital_products,saas,physical_products,service
     */
    @JsonClass(generateAdapter = false)
    enum class TaxCategory(val value: kotlin.String) {
        @Json(name = "digital_products") digital_products("digital_products"),
        @Json(name = "saas") saas("saas"),
        @Json(name = "physical_products") physical_products("physical_products"),
        @Json(name = "service") service("service");
    }
    /**
     * Pricing model of the product.
     *
     * Values: usage_based,one_time,renewal
     */
    @JsonClass(generateAdapter = false)
    enum class PricingType(val value: kotlin.String) {
        @Json(name = "usage_based") usage_based("usage_based"),
        @Json(name = "one_time") one_time("one_time"),
        @Json(name = "renewal") renewal("renewal");
    }
    /**
     * GitHub collaborator permission level.
     *
     * Values: pull,triage,push,maintain,admin
     */
    @JsonClass(generateAdapter = false)
    enum class GithubPermission(val value: kotlin.String) {
        @Json(name = "pull") pull("pull"),
        @Json(name = "triage") triage("triage"),
        @Json(name = "push") push("push"),
        @Json(name = "maintain") maintain("maintain"),
        @Json(name = "admin") admin("admin");
    }

}

