/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.Discount
import com.solifyn.model.DiscountsList200ResponsePagination

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param items 
 * @param total Total number of items matching filters.
 * @param totalCount Total number of items matching filters (alias).
 * @param pagination 
 */


data class DiscountsList200Response (

    @Json(name = "items")
    val items: kotlin.collections.List<Discount>,

    /* Total number of items matching filters. */
    @Json(name = "total")
    val total: kotlin.Int,

    /* Total number of items matching filters (alias). */
    @Json(name = "total_count")
    val totalCount: kotlin.Int,

    @Json(name = "pagination")
    val pagination: DiscountsList200ResponsePagination

) {


}

