/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Uploaded file ID
 * @param filename Name of the file
 * @param uploadUrl S3 presigned upload URL
 * @param uploadHeaders HTTP headers required for the S3 upload request
 */


data class DisputeFileUpload (

    /* Uploaded file ID */
    @Json(name = "id")
    val id: kotlin.String,

    /* Name of the file */
    @Json(name = "filename")
    val filename: kotlin.String,

    /* S3 presigned upload URL */
    @Json(name = "upload_url")
    val uploadUrl: kotlin.String? = null,

    /* HTTP headers required for the S3 upload request */
    @Json(name = "upload_headers")
    val uploadHeaders: kotlin.Any? = null

) {


}

