/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.LinkedProductDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The unique entitlement ID
 * @param businessId The owning business ID
 * @param name The name of the entitlement
 * @param type The type of access to grant
 * @param status Status of the entitlement
 * @param createdAt When the entitlement was created
 * @param updatedAt When the entitlement was last updated
 * @param grantsCount Number of active customer grants issued from this entitlement
 * @param products Products that are currently linked to this entitlement
 * @param githubRepo The GitHub repository (e.g., owner/repo)
 * @param githubPermission The GitHub repository permission level
 * @param discordGuildId The Discord Guild/Server ID
 * @param discordRoleId The Discord Role ID to assign
 * @param framerTemplateId The associated Framer Template ID
 * @param licenseKey The static License Key (if not dynamically generated)
 * @param activationLimit The maximum activation limit for licenses
 * @param activationMessage A message shown to the user upon license activation
 * @param expiryHours The number of hours until the entitlement expires
 * @param digitalLink The digital download URL or redirect link
 * @param instructions Custom setup instructions for the user
 */


data class EntitlementDetailResponseDto (

    /* The unique entitlement ID */
    @Json(name = "id")
    val id: kotlin.String,

    /* The owning business ID */
    @Json(name = "businessId")
    val businessId: kotlin.String,

    /* The name of the entitlement */
    @Json(name = "name")
    val name: kotlin.String,

    /* The type of access to grant */
    @Json(name = "type")
    val type: kotlin.String,

    /* Status of the entitlement */
    @Json(name = "status")
    val status: kotlin.String,

    /* When the entitlement was created */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* When the entitlement was last updated */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Number of active customer grants issued from this entitlement */
    @Json(name = "grantsCount")
    val grantsCount: java.math.BigDecimal,

    /* Products that are currently linked to this entitlement */
    @Json(name = "products")
    val products: kotlin.collections.List<LinkedProductDto>,

    /* The GitHub repository (e.g., owner/repo) */
    @Json(name = "githubRepo")
    val githubRepo: kotlin.String? = null,

    /* The GitHub repository permission level */
    @Json(name = "githubPermission")
    val githubPermission: kotlin.String? = null,

    /* The Discord Guild/Server ID */
    @Json(name = "discordGuildId")
    val discordGuildId: kotlin.String? = null,

    /* The Discord Role ID to assign */
    @Json(name = "discordRoleId")
    val discordRoleId: kotlin.String? = null,

    /* The associated Framer Template ID */
    @Json(name = "framerTemplateId")
    val framerTemplateId: kotlin.String? = null,

    /* The static License Key (if not dynamically generated) */
    @Json(name = "licenseKey")
    val licenseKey: kotlin.String? = null,

    /* The maximum activation limit for licenses */
    @Json(name = "activationLimit")
    val activationLimit: java.math.BigDecimal? = null,

    /* A message shown to the user upon license activation */
    @Json(name = "activationMessage")
    val activationMessage: kotlin.String? = null,

    /* The number of hours until the entitlement expires */
    @Json(name = "expiryHours")
    val expiryHours: java.math.BigDecimal? = null,

    /* The digital download URL or redirect link */
    @Json(name = "digitalLink")
    val digitalLink: kotlin.String? = null,

    /* Custom setup instructions for the user */
    @Json(name = "instructions")
    val instructions: kotlin.String? = null

) {


}

