/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a generated invoice for an order.
 *
 * @param id Unique invoice identifier.
 * @param orderId Associated order ID.
 * @param url Invoice URL for downloading or viewing PDF.
 * @param status Status of invoice.
 * @param createdAt Invoice creation date.
 */


data class Invoice (

    /* Unique invoice identifier. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Associated order ID. */
    @Json(name = "order_id")
    val orderId: kotlin.String,

    /* Invoice URL for downloading or viewing PDF. */
    @Json(name = "url")
    val url: kotlin.String,

    /* Status of invoice. */
    @Json(name = "status")
    val status: kotlin.String,

    /* Invoice creation date. */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime

) {


}

