/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.LicenseSubDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param success 
 * @param valid 
 * @param license 
 */


data class LicenseValidationResponse (

    @Json(name = "success")
    val success: kotlin.Boolean,

    @Json(name = "valid")
    val valid: kotlin.Boolean,

    @Json(name = "license")
    val license: LicenseSubDto

) {


}

