/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param instanceName A new human-readable display name for this instance.
 * @param ipAddress A new IP address to record for this instance.
 */


data class LicensesUpdateInstancePostRequest (

    /* A new human-readable display name for this instance. */
    @Json(name = "instanceName")
    val instanceName: kotlin.String? = null,

    /* A new IP address to record for this instance. */
    @Json(name = "ipAddress")
    val ipAddress: kotlin.String? = null

) {


}

