/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.ProductSubDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param key 
 * @param status 
 * @param activationLimit 
 * @param activationMessage 
 * @param expiresAt 
 * @param product 
 */


data class LicenseSubDto (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "key")
    val key: kotlin.String,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "activationLimit")
    val activationLimit: java.math.BigDecimal?,

    @Json(name = "activationMessage")
    val activationMessage: kotlin.String?,

    @Json(name = "expiresAt")
    val expiresAt: kotlin.String?,

    @Json(name = "product")
    val product: ProductSubDto? = null

) {


}

