/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.MeterIngestEventDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param events List of usage events to ingest.
 */


data class MeterIngestRequestDto (

    /* List of usage events to ingest. */
    @Json(name = "events")
    val events: kotlin.collections.List<MeterIngestEventDto>

) {


}

