/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.OperationalWebhookEndpointResponseDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param done 
 * @param iterator 
 * @param prevIterator 
 */


data class OperationalWebhookEndpointListResponseDto (

    @Json(name = "data")
    val `data`: kotlin.collections.List<OperationalWebhookEndpointResponseDto>,

    @Json(name = "done")
    val done: kotlin.Boolean,

    @Json(name = "iterator")
    val iterator: kotlin.Any? = null,

    @Json(name = "prevIterator")
    val prevIterator: kotlin.Any? = null

) {


}

