/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url The URL to send webhook events to.
 * @param description Optional description for the endpoint.
 * @param disabled Whether the endpoint is disabled.
 * @param filterTypes The operational event types this endpoint will receive.
 * @param metadata Metadata key-value pairs associated with the endpoint.
 * @param secret Optional custom endpoint signing secret (base64 encoded random bytes optionally prefixed with whsec_). If not set, the server will generate one.
 * @param throttleRate Maximum messages per second to send to this endpoint (outgoing messages will be throttled to this rate).
 * @param uid Optional unique user-defined identifier for the endpoint.
 */


data class OperationalWebhookEndpointInDto (

    /* The URL to send webhook events to. */
    @Json(name = "url")
    val url: kotlin.String,

    /* Optional description for the endpoint. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Whether the endpoint is disabled. */
    @Json(name = "disabled")
    val disabled: kotlin.Boolean? = false,

    /* The operational event types this endpoint will receive. */
    @Json(name = "filterTypes")
    val filterTypes: kotlin.collections.List<kotlin.String>? = null,

    /* Metadata key-value pairs associated with the endpoint. */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null,

    /* Optional custom endpoint signing secret (base64 encoded random bytes optionally prefixed with whsec_). If not set, the server will generate one. */
    @Json(name = "secret")
    val secret: kotlin.String? = null,

    /* Maximum messages per second to send to this endpoint (outgoing messages will be throttled to this rate). */
    @Json(name = "throttleRate")
    val throttleRate: java.math.BigDecimal? = null,

    /* Optional unique user-defined identifier for the endpoint. */
    @Json(name = "uid")
    val uid: kotlin.String? = null

) {


}

