/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param customerId The customer identifier.
 * @param email The customer email address.
 * @param name The customer name.
 * @param username The customer username.
 */


data class OrderCustomer (

    /* The customer identifier. */
    @Json(name = "customer_id")
    val customerId: kotlin.String,

    /* The customer email address. */
    @Json(name = "email")
    val email: kotlin.String,

    /* The customer name. */
    @Json(name = "name")
    val name: kotlin.String,

    /* The customer username. */
    @Json(name = "username")
    val username: kotlin.String? = null

) {


}

