/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param street 
 * @param city 
 * @param state 
 * @param zipcode 
 * @param country 
 */


data class OrderBillingUpdate (

    @Json(name = "street")
    val street: kotlin.String? = null,

    @Json(name = "city")
    val city: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.String? = null,

    @Json(name = "zipcode")
    val zipcode: kotlin.String? = null,

    @Json(name = "country")
    val country: kotlin.String? = null

) {


}

