/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param street Street address.
 * @param city City.
 * @param state State or province.
 * @param zipcode Postal or ZIP code.
 * @param country Country code.
 */


data class OrderBilling (

    /* Street address. */
    @Json(name = "street")
    val street: kotlin.String? = null,

    /* City. */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* State or province. */
    @Json(name = "state")
    val state: kotlin.String? = null,

    /* Postal or ZIP code. */
    @Json(name = "zipcode")
    val zipcode: kotlin.String? = null,

    /* Country code. */
    @Json(name = "country")
    val country: kotlin.String? = null

) {


}

