/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.PayoutVerification

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` List of verifications for the payout account
 */


data class PayoutVerificationList (

    /* List of verifications for the payout account */
    @Json(name = "data")
    val `data`: kotlin.collections.List<PayoutVerification>

) {


}

