/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.PayoutMethod

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` List of payout methods available for the business
 */


data class PayoutMethodList (

    /* List of payout methods available for the business */
    @Json(name = "data")
    val `data`: kotlin.collections.List<PayoutMethod>

) {


}

