/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param originalPrice Original price of the product after discounts
 * @param originalCurrency Original ISO currency code of the product
 * @param convertedPrice Converted price of the product
 * @param convertedCurrency Converted ISO currency code of the product
 */


data class PricePreviewResponseDto (

    /* Original price of the product after discounts */
    @Json(name = "originalPrice")
    val originalPrice: java.math.BigDecimal,

    /* Original ISO currency code of the product */
    @Json(name = "originalCurrency")
    val originalCurrency: kotlin.String,

    /* Converted price of the product */
    @Json(name = "convertedPrice")
    val convertedPrice: java.math.BigDecimal,

    /* Converted ISO currency code of the product */
    @Json(name = "convertedCurrency")
    val convertedCurrency: kotlin.String

) {


}

