/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message Response message indicating the outcome of the action.
 */


data class ProductMessageResponseDto (

    /* Response message indicating the outcome of the action. */
    @Json(name = "message")
    val message: kotlin.String

) {


}

