/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param totalCount Total number of items matching filters.
 * @param maxPage Maximum page index available based on current page size.
 */


data class ProductsList200ResponsePagination (

    /* Total number of items matching filters. */
    @Json(name = "total_count")
    val totalCount: kotlin.Int,

    /* Maximum page index available based on current page size. */
    @Json(name = "max_page")
    val maxPage: kotlin.Int

) {


}

