/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productId Unique product ID of the addon
 * @param name Display name of the addon
 * @param imageUrl URL of the addon image
 * @param quantity The purchased quantity of the addon
 */


data class ResolvedAddon (

    /* Unique product ID of the addon */
    @Json(name = "productId")
    val productId: kotlin.String,

    /* Display name of the addon */
    @Json(name = "name")
    val name: kotlin.String,

    /* URL of the addon image */
    @Json(name = "imageUrl")
    val imageUrl: kotlin.Any?,

    /* The purchased quantity of the addon */
    @Json(name = "quantity")
    val quantity: java.math.BigDecimal

) {


}

