/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.SubscriptionCompanyDto
import com.solifyn.model.SubscriptionMemberDto
import com.solifyn.model.SubscriptionPlanDto
import com.solifyn.model.SubscriptionProductDto
import com.solifyn.model.SubscriptionUserDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents a customer subscription membership resource, containing current billing terms, plan, status, and metadata.
 *
 * @param id The unique ID of the subscription
 * @param status The status of the subscription (e.g. completed, active, trialing, past_due, canceled)
 * @param createdAt Timestamp when the subscription was created
 * @param joinedAt Timestamp when the member joined
 * @param updatedAt Timestamp when the subscription was last updated
 * @param manageUrl The management URL for the billing/subscription
 * @param member The member details
 * @param user The user details
 * @param renewalPeriodStart Start timestamp of the current renewal period
 * @param renewalPeriodEnd End timestamp of the current renewal period
 * @param cancelAtPeriodEnd Whether the subscription is set to cancel at the end of the billing period
 * @param cancelOption The cancel option details
 * @param cancellationReason The reason for cancellation
 * @param canceledAt Timestamp when the subscription was canceled
 * @param currency The currency used for payments
 * @param company The company context details
 * @param plan The plan associated with this subscription
 * @param promoCode The promo code applied to the subscription
 * @param product The product associated with the subscription
 * @param licenseKey The license key associated with this subscription
 * @param metadata Additional metadata for the subscription
 * @param paymentCollectionPaused Whether the payment collection is currently paused
 * @param checkoutConfigurationId The checkout configuration ID used
 * @param price The price/amount of the membership
 * @param type The type of the membership plan
 * @param customerId The business customer ID
 */


data class Subscription (

    /* The unique ID of the subscription */
    @Json(name = "id")
    val id: kotlin.String,

    /* The status of the subscription (e.g. completed, active, trialing, past_due, canceled) */
    @Json(name = "status")
    val status: kotlin.String,

    /* Timestamp when the subscription was created */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Timestamp when the member joined */
    @Json(name = "joined_at")
    val joinedAt: java.time.OffsetDateTime,

    /* Timestamp when the subscription was last updated */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* The management URL for the billing/subscription */
    @Json(name = "manage_url")
    val manageUrl: kotlin.String,

    /* The member details */
    @Json(name = "member")
    val member: SubscriptionMemberDto,

    /* The user details */
    @Json(name = "user")
    val user: SubscriptionUserDto,

    /* Start timestamp of the current renewal period */
    @Json(name = "renewal_period_start")
    val renewalPeriodStart: kotlin.Any?,

    /* End timestamp of the current renewal period */
    @Json(name = "renewal_period_end")
    val renewalPeriodEnd: kotlin.Any?,

    /* Whether the subscription is set to cancel at the end of the billing period */
    @Json(name = "cancel_at_period_end")
    val cancelAtPeriodEnd: kotlin.Boolean,

    /* The cancel option details */
    @Json(name = "cancel_option")
    val cancelOption: kotlin.Any?,

    /* The reason for cancellation */
    @Json(name = "cancellation_reason")
    val cancellationReason: kotlin.Any?,

    /* Timestamp when the subscription was canceled */
    @Json(name = "canceled_at")
    val canceledAt: kotlin.Any?,

    /* The currency used for payments */
    @Json(name = "currency")
    val currency: kotlin.String,

    /* The company context details */
    @Json(name = "company")
    val company: SubscriptionCompanyDto,

    /* The plan associated with this subscription */
    @Json(name = "plan")
    val plan: SubscriptionPlanDto,

    /* The promo code applied to the subscription */
    @Json(name = "promo_code")
    val promoCode: kotlin.Any?,

    /* The product associated with the subscription */
    @Json(name = "product")
    val product: SubscriptionProductDto,

    /* The license key associated with this subscription */
    @Json(name = "license_key")
    val licenseKey: kotlin.Any?,

    /* Additional metadata for the subscription */
    @Json(name = "metadata")
    val metadata: kotlin.Any,

    /* Whether the payment collection is currently paused */
    @Json(name = "payment_collection_paused")
    val paymentCollectionPaused: kotlin.Boolean,

    /* The checkout configuration ID used */
    @Json(name = "checkout_configuration_id")
    val checkoutConfigurationId: kotlin.String,

    /* The price/amount of the membership */
    @Json(name = "price")
    val price: kotlin.Any? = null,

    /* The type of the membership plan */
    @Json(name = "type")
    val type: kotlin.Any? = null,

    /* The business customer ID */
    @Json(name = "customerId")
    val customerId: kotlin.Any? = null

) {


}

