/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import com.solifyn.model.Order
import com.solifyn.model.ResolvedAddon
import com.solifyn.model.Subscription
import com.solifyn.model.SubscriptionDetailProduct

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Represents detailed information about a customer subscription including active base product configuration, billing and payment history, and purchased add-ons.
 *
 * @param subscription The main subscription details
 * @param payments The subscription payments / invoice billing history
 * @param purchasedAddons List of purchased addons associated with this subscription
 * @param product The core product information associated with this subscription
 */


data class SubscriptionDetail (

    /* The main subscription details */
    @Json(name = "subscription")
    val subscription: Subscription,

    /* The subscription payments / invoice billing history */
    @Json(name = "payments")
    val payments: kotlin.collections.List<Order>,

    /* List of purchased addons associated with this subscription */
    @Json(name = "purchasedAddons")
    val purchasedAddons: kotlin.collections.List<ResolvedAddon>,

    /* The core product information associated with this subscription */
    @Json(name = "product")
    val product: SubscriptionDetailProduct?

) {


}

