/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param instanceName The updated friendly name of the instance
 * @param ipAddress The updated IP address of the client device
 */


data class UpdateInstanceDto (

    /* The updated friendly name of the instance */
    @Json(name = "instanceName")
    val instanceName: kotlin.String? = null,

    /* The updated IP address of the client device */
    @Json(name = "ipAddress")
    val ipAddress: kotlin.String? = null

) {


}

