/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name The customer friendly full name
 * @param phone The customer telephone/phone number
 * @param username The username of the customer (e.g. Discord, Whop)
 * @param metadata Custom key-value metadata associated with the customer
 */


data class UpdateCustomerDto (

    /* The customer friendly full name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* The customer telephone/phone number */
    @Json(name = "phone")
    val phone: kotlin.String? = null,

    /* The username of the customer (e.g. Discord, Whop) */
    @Json(name = "username")
    val username: kotlin.String? = null,

    /* Custom key-value metadata associated with the customer */
    @Json(name = "metadata")
    val metadata: kotlin.Any? = null

) {


}

