/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id The local withdrawal ID
 * @param whopId The Whop withdrawal ID
 * @param amount The amount withdrawn in cents
 * @param currency Three-letter ISO currency code
 * @param status The status of the withdrawal request
 * @param businessId The business ID associated with this withdrawal
 * @param createdAt Timestamp when the withdrawal was requested
 * @param updatedAt Timestamp when the withdrawal status was updated
 * @param feeAmount Fee amount charged for the withdrawal in cents
 * @param feeType The fee structure type (inclusive or exclusive)
 * @param markupFee Markup fee applied in cents
 * @param speed Speed of withdrawal (standard, instant)
 * @param traceCode Bank trace or reference code for tracking the payout
 * @param payerName The name of the entity or account paying out
 * @param errorMessage Error message if the withdrawal failed
 */


data class Withdrawal (

    /* The local withdrawal ID */
    @Json(name = "id")
    val id: kotlin.String,

    /* The Whop withdrawal ID */
    @Json(name = "whopId")
    val whopId: kotlin.String,

    /* The amount withdrawn in cents */
    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    /* Three-letter ISO currency code */
    @Json(name = "currency")
    val currency: kotlin.String,

    /* The status of the withdrawal request */
    @Json(name = "status")
    val status: kotlin.String,

    /* The business ID associated with this withdrawal */
    @Json(name = "businessId")
    val businessId: kotlin.String,

    /* Timestamp when the withdrawal was requested */
    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    /* Timestamp when the withdrawal status was updated */
    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Fee amount charged for the withdrawal in cents */
    @Json(name = "feeAmount")
    val feeAmount: java.math.BigDecimal? = null,

    /* The fee structure type (inclusive or exclusive) */
    @Json(name = "feeType")
    val feeType: kotlin.String? = null,

    /* Markup fee applied in cents */
    @Json(name = "markupFee")
    val markupFee: java.math.BigDecimal? = null,

    /* Speed of withdrawal (standard, instant) */
    @Json(name = "speed")
    val speed: kotlin.String? = null,

    /* Bank trace or reference code for tracking the payout */
    @Json(name = "traceCode")
    val traceCode: kotlin.String? = null,

    /* The name of the entity or account paying out */
    @Json(name = "payerName")
    val payerName: kotlin.String? = null,

    /* Error message if the withdrawal failed */
    @Json(name = "errorMessage")
    val errorMessage: kotlin.String? = null

) {


}

