/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.api.CheckoutApi
import com.solifyn.model.CheckoutResponseDto
import com.solifyn.model.CheckoutSessionDetailsDto
import com.solifyn.model.CreateCheckoutDto
import com.solifyn.model.CreateCollectionCheckoutDto
import com.solifyn.model.PricePreviewResponseDto
import com.solifyn.model.SupportedCurrenciesResponseDto

class CheckoutApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckoutApi
        //val apiInstance = CheckoutApi()

        // to test checkoutCreate
        should("test checkoutCreate") {
            // uncomment below to test checkoutCreate
            //val createCheckoutDto : CreateCheckoutDto =  // CreateCheckoutDto | 
            //val result : CheckoutResponseDto = apiInstance.checkoutCreate(createCheckoutDto)
            //result shouldBe ("TODO")
        }

        // to test checkoutCreateCollection
        should("test checkoutCreateCollection") {
            // uncomment below to test checkoutCreateCollection
            //val createCollectionCheckoutDto : CreateCollectionCheckoutDto =  // CreateCollectionCheckoutDto | 
            //val result : CheckoutResponseDto = apiInstance.checkoutCreateCollection(createCollectionCheckoutDto)
            //result shouldBe ("TODO")
        }

        // to test checkoutGetSession
        should("test checkoutGetSession") {
            // uncomment below to test checkoutGetSession
            //val id : kotlin.String = ch_XXXXXXXXXXX // kotlin.String | Internal database checkout session ID
            //val result : CheckoutSessionDetailsDto = apiInstance.checkoutGetSession(id)
            //result shouldBe ("TODO")
        }

        // to test checkoutPricePreview
        should("test checkoutPricePreview") {
            // uncomment below to test checkoutPricePreview
            //val productId : kotlin.String = prod_z2o92kEl6cYYX // kotlin.String | Public product ID
            //val addons : kotlin.String = addons_example // kotlin.String | 
            //val currency : kotlin.String = vnd // kotlin.String | Target currency code (ISO)
            //val discount : kotlin.String = 10 // kotlin.String | Percentage discount rate
            //val qty : kotlin.String = 1 // kotlin.String | Number of product units
            //val customPrice : kotlin.String = 15 // kotlin.String | Override price for PWYW products
            //val result : PricePreviewResponseDto = apiInstance.checkoutPricePreview(productId, addons, currency, discount, qty, customPrice)
            //result shouldBe ("TODO")
        }

        // to test checkoutSupportedCurrencies
        should("test checkoutSupportedCurrencies") {
            // uncomment below to test checkoutSupportedCurrencies
            //val result : kotlin.collections.List<SupportedCurrenciesResponseDto> = apiInstance.checkoutSupportedCurrencies()
            //result shouldBe ("TODO")
        }

    }
}
