/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.api.DeveloperApi
import com.solifyn.model.ApiKeyResponseDto
import com.solifyn.model.AppPortalUrlResponseDto
import com.solifyn.model.CreateApiKeyDto
import com.solifyn.model.CreateWebhookEndpointDto
import com.solifyn.model.UpdateWebhookEndpointDto
import com.solifyn.model.WebhookDeliveryResponseDto
import com.solifyn.model.WebhookEndpointResponseDto

class DeveloperApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeveloperApi
        //val apiInstance = DeveloperApi()

        // to test developerCreateApiKey
        should("test developerCreateApiKey") {
            // uncomment below to test developerCreateApiKey
            //val createApiKeyDto : CreateApiKeyDto =  // CreateApiKeyDto | 
            //val result : ApiKeyResponseDto = apiInstance.developerCreateApiKey(createApiKeyDto)
            //result shouldBe ("TODO")
        }

        // to test developerCreateWebhook
        should("test developerCreateWebhook") {
            // uncomment below to test developerCreateWebhook
            //val createWebhookEndpointDto : CreateWebhookEndpointDto =  // CreateWebhookEndpointDto | 
            //val result : WebhookEndpointResponseDto = apiInstance.developerCreateWebhook(createWebhookEndpointDto)
            //result shouldBe ("TODO")
        }

        // to test developerDeleteWebhook
        should("test developerDeleteWebhook") {
            // uncomment below to test developerDeleteWebhook
            //val id : kotlin.String = id_example // kotlin.String | The webhook endpoint ID
            //apiInstance.developerDeleteWebhook(id)
        }

        // to test developerGetAppPortal
        should("test developerGetAppPortal") {
            // uncomment below to test developerGetAppPortal
            //val result : AppPortalUrlResponseDto = apiInstance.developerGetAppPortal()
            //result shouldBe ("TODO")
        }

        // to test developerGetWebhook
        should("test developerGetWebhook") {
            // uncomment below to test developerGetWebhook
            //val id : kotlin.String = id_example // kotlin.String | The webhook endpoint ID
            //val result : WebhookEndpointResponseDto = apiInstance.developerGetWebhook(id)
            //result shouldBe ("TODO")
        }

        // to test developerListApiKeys
        should("test developerListApiKeys") {
            // uncomment below to test developerListApiKeys
            //val result : kotlin.collections.List<ApiKeyResponseDto> = apiInstance.developerListApiKeys()
            //result shouldBe ("TODO")
        }

        // to test developerListWebhookDeliveries
        should("test developerListWebhookDeliveries") {
            // uncomment below to test developerListWebhookDeliveries
            //val id : kotlin.String = id_example // kotlin.String | The webhook endpoint ID
            //val result : kotlin.collections.List<WebhookDeliveryResponseDto> = apiInstance.developerListWebhookDeliveries(id)
            //result shouldBe ("TODO")
        }

        // to test developerListWebhooks
        should("test developerListWebhooks") {
            // uncomment below to test developerListWebhooks
            //val result : kotlin.collections.List<WebhookEndpointResponseDto> = apiInstance.developerListWebhooks()
            //result shouldBe ("TODO")
        }

        // to test developerRevokeApiKey
        should("test developerRevokeApiKey") {
            // uncomment below to test developerRevokeApiKey
            //val id : kotlin.String = id_example // kotlin.String | The API key ID
            //apiInstance.developerRevokeApiKey(id)
        }

        // to test developerUpdateWebhook
        should("test developerUpdateWebhook") {
            // uncomment below to test developerUpdateWebhook
            //val id : kotlin.String = id_example // kotlin.String | The webhook endpoint ID
            //val updateWebhookEndpointDto : UpdateWebhookEndpointDto =  // UpdateWebhookEndpointDto | 
            //val result : WebhookEndpointResponseDto = apiInstance.developerUpdateWebhook(id, updateWebhookEndpointDto)
            //result shouldBe ("TODO")
        }

    }
}
