/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.api.FramerIntegrationApi
import com.solifyn.model.CreateFramerTemplateDto
import com.solifyn.model.FramerTemplateResponseDto
import com.solifyn.model.UpdateFramerTemplateDto

class FramerIntegrationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FramerIntegrationApi
        //val apiInstance = FramerIntegrationApi()

        // to test framerCreateTemplate
        should("test framerCreateTemplate") {
            // uncomment below to test framerCreateTemplate
            //val createFramerTemplateDto : CreateFramerTemplateDto =  // CreateFramerTemplateDto | 
            //val result : FramerTemplateResponseDto = apiInstance.framerCreateTemplate(createFramerTemplateDto)
            //result shouldBe ("TODO")
        }

        // to test framerDeleteTemplate
        should("test framerDeleteTemplate") {
            // uncomment below to test framerDeleteTemplate
            //val id : kotlin.String = id_example // kotlin.String | The Framer template ID
            //apiInstance.framerDeleteTemplate(id)
        }

        // to test framerGetTemplate
        should("test framerGetTemplate") {
            // uncomment below to test framerGetTemplate
            //val id : kotlin.String = id_example // kotlin.String | The Framer template ID
            //val result : FramerTemplateResponseDto = apiInstance.framerGetTemplate(id)
            //result shouldBe ("TODO")
        }

        // to test framerListTemplates
        should("test framerListTemplates") {
            // uncomment below to test framerListTemplates
            //val result : kotlin.collections.List<FramerTemplateResponseDto> = apiInstance.framerListTemplates()
            //result shouldBe ("TODO")
        }

        // to test framerUpdateTemplate
        should("test framerUpdateTemplate") {
            // uncomment below to test framerUpdateTemplate
            //val id : kotlin.String = id_example // kotlin.String | The Framer template ID
            //val updateFramerTemplateDto : UpdateFramerTemplateDto =  // UpdateFramerTemplateDto | 
            //val result : FramerTemplateResponseDto = apiInstance.framerUpdateTemplate(id, updateFramerTemplateDto)
            //result shouldBe ("TODO")
        }

    }
}
