/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.api.LicenseKeysClientApi
import com.solifyn.model.Instance
import com.solifyn.model.LicenseValidationResponse
import com.solifyn.model.LicensesActivateRequest
import com.solifyn.model.LicensesDeactivate200Response
import com.solifyn.model.LicensesDeactivateRequest
import com.solifyn.model.LicensesVerifyRequest

class LicenseKeysClientApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LicenseKeysClientApi
        //val apiInstance = LicenseKeysClientApi()

        // to test licensesActivate
        should("test licensesActivate") {
            // uncomment below to test licensesActivate
            //val licensesActivateRequest : LicensesActivateRequest =  // LicensesActivateRequest | 
            //val result : Instance = apiInstance.licensesActivate(licensesActivateRequest)
            //result shouldBe ("TODO")
        }

        // to test licensesDeactivate
        should("test licensesDeactivate") {
            // uncomment below to test licensesDeactivate
            //val instanceId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | The unique device instance ID.
            //val licensesDeactivateRequest : LicensesDeactivateRequest =  // LicensesDeactivateRequest | 
            //val result : LicensesDeactivate200Response = apiInstance.licensesDeactivate(instanceId, licensesDeactivateRequest)
            //result shouldBe ("TODO")
        }

        // to test licensesInstances
        should("test licensesInstances") {
            // uncomment below to test licensesInstances
            //val licenseId : java.util.UUID = 38400000-8cf0-11bd-b23e-10b96e4ef00d // java.util.UUID | The unique license key ID.
            //val result : kotlin.collections.List<Instance> = apiInstance.licensesInstances(licenseId)
            //result shouldBe ("TODO")
        }

        // to test licensesVerify
        should("test licensesVerify") {
            // uncomment below to test licensesVerify
            //val licensesVerifyRequest : LicensesVerifyRequest =  // LicensesVerifyRequest | 
            //val result : LicenseValidationResponse = apiInstance.licensesVerify(licensesVerifyRequest)
            //result shouldBe ("TODO")
        }

    }
}
