/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.api.MetersApi
import com.solifyn.model.CreateMeterDto
import com.solifyn.model.MeterDetailResponseDto
import com.solifyn.model.MeterEventsResponseDto
import com.solifyn.model.MeterIngestRequestDto
import com.solifyn.model.MeterIngestResponseDto
import com.solifyn.model.MeterQuantitiesResponseDto
import com.solifyn.model.MeterResponseDto
import com.solifyn.model.UpdateMeterDto

class MetersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MetersApi
        //val apiInstance = MetersApi()

        // to test eventsIngest
        should("test eventsIngest") {
            // uncomment below to test eventsIngest
            //val meterIngestRequestDto : MeterIngestRequestDto =  // MeterIngestRequestDto | 
            //val result : MeterIngestResponseDto = apiInstance.eventsIngest(meterIngestRequestDto)
            //result shouldBe ("TODO")
        }

        // to test metersCreate
        should("test metersCreate") {
            // uncomment below to test metersCreate
            //val createMeterDto : CreateMeterDto =  // CreateMeterDto | 
            //val result : MeterResponseDto = apiInstance.metersCreate(createMeterDto)
            //result shouldBe ("TODO")
        }

        // to test metersGet
        should("test metersGet") {
            // uncomment below to test metersGet
            //val id : kotlin.String = mtr_8Z1aB2cD3eF4gH5iJ6kL7m // kotlin.String | The unique meter ID.
            //val startDate : kotlin.String = startDate_example // kotlin.String | 
            //val endDate : kotlin.String = endDate_example // kotlin.String | 
            //val result : MeterDetailResponseDto = apiInstance.metersGet(id, startDate, endDate)
            //result shouldBe ("TODO")
        }

        // to test metersGetEvents
        should("test metersGetEvents") {
            // uncomment below to test metersGetEvents
            //val id : kotlin.String = mtr_8Z1aB2cD3eF4gH5iJ6kL7m // kotlin.String | The unique meter ID.
            //val limit : java.math.BigDecimal = 8.14 // java.math.BigDecimal | Maximum number of usage events to return.
            //val result : MeterEventsResponseDto = apiInstance.metersGetEvents(id, limit)
            //result shouldBe ("TODO")
        }

        // to test metersGetQuantities
        should("test metersGetQuantities") {
            // uncomment below to test metersGetQuantities
            //val id : kotlin.String = mtr_8Z1aB2cD3eF4gH5iJ6kL7m // kotlin.String | The unique meter ID.
            //val startDate : kotlin.String = startDate_example // kotlin.String | Inclusive start date in ISO 8601 format.
            //val endDate : kotlin.String = endDate_example // kotlin.String | Inclusive end date in ISO 8601 format.
            //val result : MeterQuantitiesResponseDto = apiInstance.metersGetQuantities(id, startDate, endDate)
            //result shouldBe ("TODO")
        }

        // to test metersList
        should("test metersList") {
            // uncomment below to test metersList
            //val status : kotlin.String = status_example // kotlin.String | Filter by meter status.
            //val result : kotlin.collections.List<MeterResponseDto> = apiInstance.metersList(status)
            //result shouldBe ("TODO")
        }

        // to test metersUpdate
        should("test metersUpdate") {
            // uncomment below to test metersUpdate
            //val id : kotlin.String = mtr_8Z1aB2cD3eF4gH5iJ6kL7m // kotlin.String | The unique meter ID.
            //val updateMeterDto : UpdateMeterDto =  // UpdateMeterDto | 
            //val result : MeterResponseDto = apiInstance.metersUpdate(id, updateMeterDto)
            //result shouldBe ("TODO")
        }

    }
}
