/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.solifyn.model.AddCollectionProductsDto
import com.solifyn.model.CollectionArchivedResponseDto
import com.solifyn.model.CollectionDetailResponseDto
import com.solifyn.model.CollectionProductDeletedResponseDto
import com.solifyn.model.CollectionProductUpdatedResponseDto
import com.solifyn.model.CollectionResponseDto
import com.solifyn.model.CollectionUnarchivedResponseDto
import com.solifyn.model.CollectionUpdatedResponseDto
import com.solifyn.model.CreateCollectionDto
import com.solifyn.model.UpdateCollectionDto
import com.solifyn.model.UpdateCollectionProductDto

import com.squareup.moshi.Json

import com.solifyn.infrastructure.ApiClient
import com.solifyn.infrastructure.ApiResponse
import com.solifyn.infrastructure.ClientException
import com.solifyn.infrastructure.ClientError
import com.solifyn.infrastructure.ServerException
import com.solifyn.infrastructure.ServerError
import com.solifyn.infrastructure.MultiValueMap
import com.solifyn.infrastructure.PartConfig
import com.solifyn.infrastructure.RequestConfig
import com.solifyn.infrastructure.RequestMethod
import com.solifyn.infrastructure.ResponseType
import com.solifyn.infrastructure.Success
import com.solifyn.infrastructure.toMultiValue

class CollectionsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.solifyn.com")
        }
    }

    /**
     * Add Products to Collection
     * Add one or more products to a collection. If a product already exists, its quantity is updated.
     * @param id Collection ID
     * @param addCollectionProductsDto 
     * @return CollectionResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsAddProducts(id: kotlin.String, addCollectionProductsDto: AddCollectionProductsDto) : CollectionResponseDto {
        val localVarResponse = collectionsAddProductsWithHttpInfo(id = id, addCollectionProductsDto = addCollectionProductsDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Add Products to Collection
     * Add one or more products to a collection. If a product already exists, its quantity is updated.
     * @param id Collection ID
     * @param addCollectionProductsDto 
     * @return ApiResponse<CollectionResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsAddProductsWithHttpInfo(id: kotlin.String, addCollectionProductsDto: AddCollectionProductsDto) : ApiResponse<CollectionResponseDto?> {
        val localVariableConfig = collectionsAddProductsRequestConfig(id = id, addCollectionProductsDto = addCollectionProductsDto)

        return request<AddCollectionProductsDto, CollectionResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsAddProducts
     *
     * @param id Collection ID
     * @param addCollectionProductsDto 
     * @return RequestConfig
     */
    fun collectionsAddProductsRequestConfig(id: kotlin.String, addCollectionProductsDto: AddCollectionProductsDto) : RequestConfig<AddCollectionProductsDto> {
        val localVariableBody = addCollectionProductsDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/collections/{id}/products".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Archive Collection
     * Deactivate and move a collection to archives.
     * @param id Collection ID
     * @return CollectionArchivedResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsArchive(id: kotlin.String) : CollectionArchivedResponseDto {
        val localVarResponse = collectionsArchiveWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionArchivedResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Archive Collection
     * Deactivate and move a collection to archives.
     * @param id Collection ID
     * @return ApiResponse<CollectionArchivedResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsArchiveWithHttpInfo(id: kotlin.String) : ApiResponse<CollectionArchivedResponseDto?> {
        val localVariableConfig = collectionsArchiveRequestConfig(id = id)

        return request<Unit, CollectionArchivedResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsArchive
     *
     * @param id Collection ID
     * @return RequestConfig
     */
    fun collectionsArchiveRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/collections/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Create Collection
     * Generate a new product collection for checkout packaging.
     * @param createCollectionDto 
     * @return CollectionResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsCreate(createCollectionDto: CreateCollectionDto) : CollectionResponseDto {
        val localVarResponse = collectionsCreateWithHttpInfo(createCollectionDto = createCollectionDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Create Collection
     * Generate a new product collection for checkout packaging.
     * @param createCollectionDto 
     * @return ApiResponse<CollectionResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsCreateWithHttpInfo(createCollectionDto: CreateCollectionDto) : ApiResponse<CollectionResponseDto?> {
        val localVariableConfig = collectionsCreateRequestConfig(createCollectionDto = createCollectionDto)

        return request<CreateCollectionDto, CollectionResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsCreate
     *
     * @param createCollectionDto 
     * @return RequestConfig
     */
    fun collectionsCreateRequestConfig(createCollectionDto: CreateCollectionDto) : RequestConfig<CreateCollectionDto> {
        val localVariableBody = createCollectionDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/collections",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Remove Product from Collection
     * Remove a product from a collection.
     * @param id Collection ID
     * @param productId Product ID
     * @return CollectionProductDeletedResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsDeleteProduct(id: kotlin.String, productId: kotlin.String) : CollectionProductDeletedResponseDto {
        val localVarResponse = collectionsDeleteProductWithHttpInfo(id = id, productId = productId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionProductDeletedResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Remove Product from Collection
     * Remove a product from a collection.
     * @param id Collection ID
     * @param productId Product ID
     * @return ApiResponse<CollectionProductDeletedResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsDeleteProductWithHttpInfo(id: kotlin.String, productId: kotlin.String) : ApiResponse<CollectionProductDeletedResponseDto?> {
        val localVariableConfig = collectionsDeleteProductRequestConfig(id = id, productId = productId)

        return request<Unit, CollectionProductDeletedResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsDeleteProduct
     *
     * @param id Collection ID
     * @param productId Product ID
     * @return RequestConfig
     */
    fun collectionsDeleteProductRequestConfig(id: kotlin.String, productId: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/collections/{id}/products/{productId}".replace("{"+"id"+"}", encodeURIComponent(id.toString())).replace("{"+"productId"+"}", encodeURIComponent(productId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Retrieve Collection
     * Get properties of a product collection by ID.
     * @param id Collection ID
     * @return CollectionDetailResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsGet(id: kotlin.String) : CollectionDetailResponseDto {
        val localVarResponse = collectionsGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionDetailResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieve Collection
     * Get properties of a product collection by ID.
     * @param id Collection ID
     * @return ApiResponse<CollectionDetailResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsGetWithHttpInfo(id: kotlin.String) : ApiResponse<CollectionDetailResponseDto?> {
        val localVariableConfig = collectionsGetRequestConfig(id = id)

        return request<Unit, CollectionDetailResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsGet
     *
     * @param id Collection ID
     * @return RequestConfig
     */
    fun collectionsGetRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/collections/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List Collections
     * Get all active product collections linked to the current active business.
     * @return kotlin.collections.List<CollectionResponseDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsList() : kotlin.collections.List<CollectionResponseDto> {
        val localVarResponse = collectionsListWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CollectionResponseDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List Collections
     * Get all active product collections linked to the current active business.
     * @return ApiResponse<kotlin.collections.List<CollectionResponseDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsListWithHttpInfo() : ApiResponse<kotlin.collections.List<CollectionResponseDto>?> {
        val localVariableConfig = collectionsListRequestConfig()

        return request<Unit, kotlin.collections.List<CollectionResponseDto>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsList
     *
     * @return RequestConfig
     */
    fun collectionsListRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/collections",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List Archived Collections
     * Get all archived/deactivated product collections.
     * @return kotlin.collections.List<CollectionResponseDto>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsListArchived() : kotlin.collections.List<CollectionResponseDto> {
        val localVarResponse = collectionsListArchivedWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CollectionResponseDto>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List Archived Collections
     * Get all archived/deactivated product collections.
     * @return ApiResponse<kotlin.collections.List<CollectionResponseDto>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsListArchivedWithHttpInfo() : ApiResponse<kotlin.collections.List<CollectionResponseDto>?> {
        val localVariableConfig = collectionsListArchivedRequestConfig()

        return request<Unit, kotlin.collections.List<CollectionResponseDto>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsListArchived
     *
     * @return RequestConfig
     */
    fun collectionsListArchivedRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/collections/archived",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Unarchive Collection
     * Restore an archived collection back to active status.
     * @param id Collection ID
     * @return CollectionUnarchivedResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsUnarchive(id: kotlin.String) : CollectionUnarchivedResponseDto {
        val localVarResponse = collectionsUnarchiveWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionUnarchivedResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Unarchive Collection
     * Restore an archived collection back to active status.
     * @param id Collection ID
     * @return ApiResponse<CollectionUnarchivedResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsUnarchiveWithHttpInfo(id: kotlin.String) : ApiResponse<CollectionUnarchivedResponseDto?> {
        val localVariableConfig = collectionsUnarchiveRequestConfig(id = id)

        return request<Unit, CollectionUnarchivedResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsUnarchive
     *
     * @param id Collection ID
     * @return RequestConfig
     */
    fun collectionsUnarchiveRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/collections/{id}/unarchive".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Update Collection
     * Update products, friendly name, status, or description of a collection.
     * @param id Collection ID
     * @param updateCollectionDto 
     * @return CollectionUpdatedResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsUpdate(id: kotlin.String, updateCollectionDto: UpdateCollectionDto) : CollectionUpdatedResponseDto {
        val localVarResponse = collectionsUpdateWithHttpInfo(id = id, updateCollectionDto = updateCollectionDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionUpdatedResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update Collection
     * Update products, friendly name, status, or description of a collection.
     * @param id Collection ID
     * @param updateCollectionDto 
     * @return ApiResponse<CollectionUpdatedResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsUpdateWithHttpInfo(id: kotlin.String, updateCollectionDto: UpdateCollectionDto) : ApiResponse<CollectionUpdatedResponseDto?> {
        val localVariableConfig = collectionsUpdateRequestConfig(id = id, updateCollectionDto = updateCollectionDto)

        return request<UpdateCollectionDto, CollectionUpdatedResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsUpdate
     *
     * @param id Collection ID
     * @param updateCollectionDto 
     * @return RequestConfig
     */
    fun collectionsUpdateRequestConfig(id: kotlin.String, updateCollectionDto: UpdateCollectionDto) : RequestConfig<UpdateCollectionDto> {
        val localVariableBody = updateCollectionDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/collections/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Update Collection Product
     * Update quantity of a specific product inside a collection.
     * @param id Collection ID
     * @param productId Product ID
     * @param updateCollectionProductDto 
     * @return CollectionProductUpdatedResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun collectionsUpdateProduct(id: kotlin.String, productId: kotlin.String, updateCollectionProductDto: UpdateCollectionProductDto) : CollectionProductUpdatedResponseDto {
        val localVarResponse = collectionsUpdateProductWithHttpInfo(id = id, productId = productId, updateCollectionProductDto = updateCollectionProductDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CollectionProductUpdatedResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update Collection Product
     * Update quantity of a specific product inside a collection.
     * @param id Collection ID
     * @param productId Product ID
     * @param updateCollectionProductDto 
     * @return ApiResponse<CollectionProductUpdatedResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun collectionsUpdateProductWithHttpInfo(id: kotlin.String, productId: kotlin.String, updateCollectionProductDto: UpdateCollectionProductDto) : ApiResponse<CollectionProductUpdatedResponseDto?> {
        val localVariableConfig = collectionsUpdateProductRequestConfig(id = id, productId = productId, updateCollectionProductDto = updateCollectionProductDto)

        return request<UpdateCollectionProductDto, CollectionProductUpdatedResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation collectionsUpdateProduct
     *
     * @param id Collection ID
     * @param productId Product ID
     * @param updateCollectionProductDto 
     * @return RequestConfig
     */
    fun collectionsUpdateProductRequestConfig(id: kotlin.String, productId: kotlin.String, updateCollectionProductDto: UpdateCollectionProductDto) : RequestConfig<UpdateCollectionProductDto> {
        val localVariableBody = updateCollectionProductDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/collections/{id}/products/{productId}".replace("{"+"id"+"}", encodeURIComponent(id.toString())).replace("{"+"productId"+"}", encodeURIComponent(productId.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
