/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.solifyn.model.License
import com.solifyn.model.Order
import com.solifyn.model.UNKNOWN_BASE_TYPE

import com.squareup.moshi.Json

import com.solifyn.infrastructure.ApiClient
import com.solifyn.infrastructure.ApiResponse
import com.solifyn.infrastructure.ClientException
import com.solifyn.infrastructure.ClientError
import com.solifyn.infrastructure.ServerException
import com.solifyn.infrastructure.ServerError
import com.solifyn.infrastructure.MultiValueMap
import com.solifyn.infrastructure.PartConfig
import com.solifyn.infrastructure.RequestConfig
import com.solifyn.infrastructure.RequestMethod
import com.solifyn.infrastructure.ResponseType
import com.solifyn.infrastructure.Success
import com.solifyn.infrastructure.toMultiValue

class DefaultApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8000")
        }
    }

    /**
     * Dispute Created
     * Occurs when a payment charge is disputed by the customer (chargeback initiated).
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputeCreatedPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = disputeCreatedPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Dispute Created
     * Occurs when a payment charge is disputed by the customer (chargeback initiated).
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun disputeCreatedPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = disputeCreatedPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputeCreatedPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun disputeCreatedPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/dispute.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Dispute Lost
     * Occurs when a dispute challenge is lost and the funds are returned to the cardholder.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputeLostPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = disputeLostPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Dispute Lost
     * Occurs when a dispute challenge is lost and the funds are returned to the cardholder.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun disputeLostPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = disputeLostPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputeLostPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun disputeLostPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/dispute.lost",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Dispute Won
     * Occurs when a dispute challenge is won by the merchant.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputeWonPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = disputeWonPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Dispute Won
     * Occurs when a dispute challenge is won by the merchant.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun disputeWonPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = disputeWonPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputeWonPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun disputeWonPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/dispute.won",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * License Created
     * Occurs when a new software license key is created or assigned to a customer purchase.
     * @param license  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun licenseCreatedPost(license: License? = null) : Unit {
        val localVarResponse = licenseCreatedPostWithHttpInfo(license = license)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * License Created
     * Occurs when a new software license key is created or assigned to a customer purchase.
     * @param license  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun licenseCreatedPostWithHttpInfo(license: License?) : ApiResponse<Unit?> {
        val localVariableConfig = licenseCreatedPostRequestConfig(license = license)

        return request<License, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation licenseCreatedPost
     *
     * @param license  (optional)
     * @return RequestConfig
     */
    fun licenseCreatedPostRequestConfig(license: License?) : RequestConfig<License> {
        val localVariableBody = license
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/license.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * License Revoked
     * Occurs when a software license key is revoked (e.g., due to subscription cancellation, refund, or dispute).
     * @param license  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun licenseRevokedPost(license: License? = null) : Unit {
        val localVarResponse = licenseRevokedPostWithHttpInfo(license = license)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * License Revoked
     * Occurs when a software license key is revoked (e.g., due to subscription cancellation, refund, or dispute).
     * @param license  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun licenseRevokedPostWithHttpInfo(license: License?) : ApiResponse<Unit?> {
        val localVariableConfig = licenseRevokedPostRequestConfig(license = license)

        return request<License, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation licenseRevokedPost
     *
     * @param license  (optional)
     * @return RequestConfig
     */
    fun licenseRevokedPostRequestConfig(license: License?) : RequestConfig<License> {
        val localVariableBody = license
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/license.revoked",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Payment Created
     * Occurs when a new payment is initiated (e.g., at checkout start or subscription creation). The payment may still be in an incomplete or pending state.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun paymentCreatedPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = paymentCreatedPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Payment Created
     * Occurs when a new payment is initiated (e.g., at checkout start or subscription creation). The payment may still be in an incomplete or pending state.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun paymentCreatedPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = paymentCreatedPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation paymentCreatedPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun paymentCreatedPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/payment.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Payment Failed
     * Occurs when a customer payment attempt fails.
     * @param order  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun paymentFailedPost(order: Order? = null) : Unit {
        val localVarResponse = paymentFailedPostWithHttpInfo(order = order)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Payment Failed
     * Occurs when a customer payment attempt fails.
     * @param order  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun paymentFailedPostWithHttpInfo(order: Order?) : ApiResponse<Unit?> {
        val localVariableConfig = paymentFailedPostRequestConfig(order = order)

        return request<Order, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation paymentFailedPost
     *
     * @param order  (optional)
     * @return RequestConfig
     */
    fun paymentFailedPostRequestConfig(order: Order?) : RequestConfig<Order> {
        val localVariableBody = order
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/payment.failed",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Payment Succeeded
     * Occurs when a customer payment is confirmed as succeeded.
     * @param order  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun paymentSucceededPost(order: Order? = null) : Unit {
        val localVarResponse = paymentSucceededPostWithHttpInfo(order = order)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Payment Succeeded
     * Occurs when a customer payment is confirmed as succeeded.
     * @param order  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun paymentSucceededPostWithHttpInfo(order: Order?) : ApiResponse<Unit?> {
        val localVariableConfig = paymentSucceededPostRequestConfig(order = order)

        return request<Order, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation paymentSucceededPost
     *
     * @param order  (optional)
     * @return RequestConfig
     */
    fun paymentSucceededPostRequestConfig(order: Order?) : RequestConfig<Order> {
        val localVariableBody = order
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/payment.succeeded",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Refund Failed
     * Occurs when a payment refund fails.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refundFailedPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = refundFailedPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Refund Failed
     * Occurs when a payment refund fails.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun refundFailedPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = refundFailedPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation refundFailedPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun refundFailedPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/refund.failed",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Refund Succeeded
     * Occurs when a payment refund is confirmed as succeeded.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refundSucceededPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = refundSucceededPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Refund Succeeded
     * Occurs when a payment refund is confirmed as succeeded.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun refundSucceededPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = refundSucceededPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation refundSucceededPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun refundSucceededPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/refund.succeeded",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Subscription Created
     * Occurs when a customer subscription is successfully started.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionCreatedPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = subscriptionCreatedPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Subscription Created
     * Occurs when a customer subscription is successfully started.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionCreatedPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = subscriptionCreatedPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionCreatedPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun subscriptionCreatedPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/subscription.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Subscription Deactivated
     * Occurs when a customer subscription is deactivated or expired.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionDeactivatedPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = subscriptionDeactivatedPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Subscription Deactivated
     * Occurs when a customer subscription is deactivated or expired.
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionDeactivatedPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = subscriptionDeactivatedPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionDeactivatedPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun subscriptionDeactivatedPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/subscription.deactivated",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Subscription Updated
     * Occurs when a customer subscription is updated (e.g., cancel at period end changes).
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionUpdatedPost(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE? = null) : Unit {
        val localVarResponse = subscriptionUpdatedPostWithHttpInfo(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Subscription Updated
     * Occurs when a customer subscription is updated (e.g., cancel at period end changes).
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionUpdatedPostWithHttpInfo(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : ApiResponse<Unit?> {
        val localVariableConfig = subscriptionUpdatedPostRequestConfig(UNKNOWN_BASE_TYPE = UNKNOWN_BASE_TYPE)

        return request<UNKNOWN_BASE_TYPE, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionUpdatedPost
     *
     * @param UNKNOWN_BASE_TYPE  (optional)
     * @return RequestConfig
     */
    fun subscriptionUpdatedPostRequestConfig(UNKNOWN_BASE_TYPE: UNKNOWN_BASE_TYPE?) : RequestConfig<UNKNOWN_BASE_TYPE> {
        val localVariableBody = UNKNOWN_BASE_TYPE
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/subscription.updated",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
