/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.solifyn.model.Order
import com.solifyn.model.WebhookDisputePayload
import com.solifyn.model.WebhookEntitlementGrantPayload
import com.solifyn.model.WebhookLicensePayload
import com.solifyn.model.WebhookPaymentPayload
import com.solifyn.model.WebhookRefundPayload
import com.solifyn.model.WebhookSubscriptionPayload

import com.squareup.moshi.Json

import com.solifyn.infrastructure.ApiClient
import com.solifyn.infrastructure.ApiResponse
import com.solifyn.infrastructure.ClientException
import com.solifyn.infrastructure.ClientError
import com.solifyn.infrastructure.ServerException
import com.solifyn.infrastructure.ServerError
import com.solifyn.infrastructure.MultiValueMap
import com.solifyn.infrastructure.PartConfig
import com.solifyn.infrastructure.RequestConfig
import com.solifyn.infrastructure.RequestMethod
import com.solifyn.infrastructure.ResponseType
import com.solifyn.infrastructure.Success
import com.solifyn.infrastructure.toMultiValue

class DefaultApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "https://api.solifyn.com")
        }
    }

    /**
     * Dispute Created
     * Occurs when a payment charge is disputed by the customer (chargeback initiated).
     * @param webhookDisputePayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputeCreatedPost(webhookDisputePayload: WebhookDisputePayload? = null) : Unit {
        val localVarResponse = disputeCreatedPostWithHttpInfo(webhookDisputePayload = webhookDisputePayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Dispute Created
     * Occurs when a payment charge is disputed by the customer (chargeback initiated).
     * @param webhookDisputePayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun disputeCreatedPostWithHttpInfo(webhookDisputePayload: WebhookDisputePayload?) : ApiResponse<Unit?> {
        val localVariableConfig = disputeCreatedPostRequestConfig(webhookDisputePayload = webhookDisputePayload)

        return request<WebhookDisputePayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputeCreatedPost
     *
     * @param webhookDisputePayload  (optional)
     * @return RequestConfig
     */
    fun disputeCreatedPostRequestConfig(webhookDisputePayload: WebhookDisputePayload?) : RequestConfig<WebhookDisputePayload> {
        val localVariableBody = webhookDisputePayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/dispute.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Dispute Lost
     * Occurs when a dispute challenge is lost and the funds are returned to the cardholder.
     * @param webhookDisputePayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputeLostPost(webhookDisputePayload: WebhookDisputePayload? = null) : Unit {
        val localVarResponse = disputeLostPostWithHttpInfo(webhookDisputePayload = webhookDisputePayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Dispute Lost
     * Occurs when a dispute challenge is lost and the funds are returned to the cardholder.
     * @param webhookDisputePayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun disputeLostPostWithHttpInfo(webhookDisputePayload: WebhookDisputePayload?) : ApiResponse<Unit?> {
        val localVariableConfig = disputeLostPostRequestConfig(webhookDisputePayload = webhookDisputePayload)

        return request<WebhookDisputePayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputeLostPost
     *
     * @param webhookDisputePayload  (optional)
     * @return RequestConfig
     */
    fun disputeLostPostRequestConfig(webhookDisputePayload: WebhookDisputePayload?) : RequestConfig<WebhookDisputePayload> {
        val localVariableBody = webhookDisputePayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/dispute.lost",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Dispute Won
     * Occurs when a dispute challenge is won by the merchant.
     * @param webhookDisputePayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputeWonPost(webhookDisputePayload: WebhookDisputePayload? = null) : Unit {
        val localVarResponse = disputeWonPostWithHttpInfo(webhookDisputePayload = webhookDisputePayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Dispute Won
     * Occurs when a dispute challenge is won by the merchant.
     * @param webhookDisputePayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun disputeWonPostWithHttpInfo(webhookDisputePayload: WebhookDisputePayload?) : ApiResponse<Unit?> {
        val localVariableConfig = disputeWonPostRequestConfig(webhookDisputePayload = webhookDisputePayload)

        return request<WebhookDisputePayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputeWonPost
     *
     * @param webhookDisputePayload  (optional)
     * @return RequestConfig
     */
    fun disputeWonPostRequestConfig(webhookDisputePayload: WebhookDisputePayload?) : RequestConfig<WebhookDisputePayload> {
        val localVariableBody = webhookDisputePayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/dispute.won",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Entitlement Grant Created
     * Occurs when a new entitlement grant is created (e.g., at checkout completion if the product has GitHub access). The collaborator invitation is pending.
     * @param webhookEntitlementGrantPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun entitlementGrantCreatedPost(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload? = null) : Unit {
        val localVarResponse = entitlementGrantCreatedPostWithHttpInfo(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Entitlement Grant Created
     * Occurs when a new entitlement grant is created (e.g., at checkout completion if the product has GitHub access). The collaborator invitation is pending.
     * @param webhookEntitlementGrantPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun entitlementGrantCreatedPostWithHttpInfo(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = entitlementGrantCreatedPostRequestConfig(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return request<WebhookEntitlementGrantPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation entitlementGrantCreatedPost
     *
     * @param webhookEntitlementGrantPayload  (optional)
     * @return RequestConfig
     */
    fun entitlementGrantCreatedPostRequestConfig(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : RequestConfig<WebhookEntitlementGrantPayload> {
        val localVariableBody = webhookEntitlementGrantPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/entitlement_grant.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Entitlement Grant Delivered
     * Occurs when the customer successfully connects their GitHub account and the collaborator invitation is successfully delivered.
     * @param webhookEntitlementGrantPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun entitlementGrantDeliveredPost(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload? = null) : Unit {
        val localVarResponse = entitlementGrantDeliveredPostWithHttpInfo(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Entitlement Grant Delivered
     * Occurs when the customer successfully connects their GitHub account and the collaborator invitation is successfully delivered.
     * @param webhookEntitlementGrantPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun entitlementGrantDeliveredPostWithHttpInfo(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = entitlementGrantDeliveredPostRequestConfig(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return request<WebhookEntitlementGrantPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation entitlementGrantDeliveredPost
     *
     * @param webhookEntitlementGrantPayload  (optional)
     * @return RequestConfig
     */
    fun entitlementGrantDeliveredPostRequestConfig(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : RequestConfig<WebhookEntitlementGrantPayload> {
        val localVariableBody = webhookEntitlementGrantPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/entitlement_grant.delivered",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Entitlement Grant Failed
     * Occurs when invitation delivery fails (e.g., if the user GitHub account is flagged or invitation limit is reached).
     * @param webhookEntitlementGrantPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun entitlementGrantFailedPost(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload? = null) : Unit {
        val localVarResponse = entitlementGrantFailedPostWithHttpInfo(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Entitlement Grant Failed
     * Occurs when invitation delivery fails (e.g., if the user GitHub account is flagged or invitation limit is reached).
     * @param webhookEntitlementGrantPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun entitlementGrantFailedPostWithHttpInfo(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = entitlementGrantFailedPostRequestConfig(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return request<WebhookEntitlementGrantPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation entitlementGrantFailedPost
     *
     * @param webhookEntitlementGrantPayload  (optional)
     * @return RequestConfig
     */
    fun entitlementGrantFailedPostRequestConfig(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : RequestConfig<WebhookEntitlementGrantPayload> {
        val localVariableBody = webhookEntitlementGrantPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/entitlement_grant.failed",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Entitlement Grant Revoked
     * Occurs when the customer access is removed from the repository (manually or automatically via subscription cancel/refund).
     * @param webhookEntitlementGrantPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun entitlementGrantRevokedPost(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload? = null) : Unit {
        val localVarResponse = entitlementGrantRevokedPostWithHttpInfo(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Entitlement Grant Revoked
     * Occurs when the customer access is removed from the repository (manually or automatically via subscription cancel/refund).
     * @param webhookEntitlementGrantPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun entitlementGrantRevokedPostWithHttpInfo(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = entitlementGrantRevokedPostRequestConfig(webhookEntitlementGrantPayload = webhookEntitlementGrantPayload)

        return request<WebhookEntitlementGrantPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation entitlementGrantRevokedPost
     *
     * @param webhookEntitlementGrantPayload  (optional)
     * @return RequestConfig
     */
    fun entitlementGrantRevokedPostRequestConfig(webhookEntitlementGrantPayload: WebhookEntitlementGrantPayload?) : RequestConfig<WebhookEntitlementGrantPayload> {
        val localVariableBody = webhookEntitlementGrantPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/entitlement_grant.revoked",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * License Created
     * Occurs when a new software license key is created or assigned to a customer purchase.
     * @param webhookLicensePayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun licenseCreatedPost(webhookLicensePayload: WebhookLicensePayload? = null) : Unit {
        val localVarResponse = licenseCreatedPostWithHttpInfo(webhookLicensePayload = webhookLicensePayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * License Created
     * Occurs when a new software license key is created or assigned to a customer purchase.
     * @param webhookLicensePayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun licenseCreatedPostWithHttpInfo(webhookLicensePayload: WebhookLicensePayload?) : ApiResponse<Unit?> {
        val localVariableConfig = licenseCreatedPostRequestConfig(webhookLicensePayload = webhookLicensePayload)

        return request<WebhookLicensePayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation licenseCreatedPost
     *
     * @param webhookLicensePayload  (optional)
     * @return RequestConfig
     */
    fun licenseCreatedPostRequestConfig(webhookLicensePayload: WebhookLicensePayload?) : RequestConfig<WebhookLicensePayload> {
        val localVariableBody = webhookLicensePayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/license.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * License Revoked
     * Occurs when a software license key is revoked (e.g., due to subscription cancellation, refund, or dispute).
     * @param webhookLicensePayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun licenseRevokedPost(webhookLicensePayload: WebhookLicensePayload? = null) : Unit {
        val localVarResponse = licenseRevokedPostWithHttpInfo(webhookLicensePayload = webhookLicensePayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * License Revoked
     * Occurs when a software license key is revoked (e.g., due to subscription cancellation, refund, or dispute).
     * @param webhookLicensePayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun licenseRevokedPostWithHttpInfo(webhookLicensePayload: WebhookLicensePayload?) : ApiResponse<Unit?> {
        val localVariableConfig = licenseRevokedPostRequestConfig(webhookLicensePayload = webhookLicensePayload)

        return request<WebhookLicensePayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation licenseRevokedPost
     *
     * @param webhookLicensePayload  (optional)
     * @return RequestConfig
     */
    fun licenseRevokedPostRequestConfig(webhookLicensePayload: WebhookLicensePayload?) : RequestConfig<WebhookLicensePayload> {
        val localVariableBody = webhookLicensePayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/license.revoked",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Payment Created
     * Occurs when a new payment is initiated (e.g., at checkout start or subscription creation). The payment may still be in an incomplete or pending state.
     * @param webhookPaymentPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun paymentCreatedPost(webhookPaymentPayload: WebhookPaymentPayload? = null) : Unit {
        val localVarResponse = paymentCreatedPostWithHttpInfo(webhookPaymentPayload = webhookPaymentPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Payment Created
     * Occurs when a new payment is initiated (e.g., at checkout start or subscription creation). The payment may still be in an incomplete or pending state.
     * @param webhookPaymentPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun paymentCreatedPostWithHttpInfo(webhookPaymentPayload: WebhookPaymentPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = paymentCreatedPostRequestConfig(webhookPaymentPayload = webhookPaymentPayload)

        return request<WebhookPaymentPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation paymentCreatedPost
     *
     * @param webhookPaymentPayload  (optional)
     * @return RequestConfig
     */
    fun paymentCreatedPostRequestConfig(webhookPaymentPayload: WebhookPaymentPayload?) : RequestConfig<WebhookPaymentPayload> {
        val localVariableBody = webhookPaymentPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/payment.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Payment Failed
     * Occurs when a customer payment attempt fails.
     * @param order  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun paymentFailedPost(order: Order? = null) : Unit {
        val localVarResponse = paymentFailedPostWithHttpInfo(order = order)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Payment Failed
     * Occurs when a customer payment attempt fails.
     * @param order  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun paymentFailedPostWithHttpInfo(order: Order?) : ApiResponse<Unit?> {
        val localVariableConfig = paymentFailedPostRequestConfig(order = order)

        return request<Order, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation paymentFailedPost
     *
     * @param order  (optional)
     * @return RequestConfig
     */
    fun paymentFailedPostRequestConfig(order: Order?) : RequestConfig<Order> {
        val localVariableBody = order
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/payment.failed",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Payment Succeeded
     * Occurs when a customer payment is confirmed as succeeded.
     * @param order  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun paymentSucceededPost(order: Order? = null) : Unit {
        val localVarResponse = paymentSucceededPostWithHttpInfo(order = order)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Payment Succeeded
     * Occurs when a customer payment is confirmed as succeeded.
     * @param order  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun paymentSucceededPostWithHttpInfo(order: Order?) : ApiResponse<Unit?> {
        val localVariableConfig = paymentSucceededPostRequestConfig(order = order)

        return request<Order, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation paymentSucceededPost
     *
     * @param order  (optional)
     * @return RequestConfig
     */
    fun paymentSucceededPostRequestConfig(order: Order?) : RequestConfig<Order> {
        val localVariableBody = order
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/payment.succeeded",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Refund Failed
     * Occurs when a payment refund fails.
     * @param webhookRefundPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refundFailedPost(webhookRefundPayload: WebhookRefundPayload? = null) : Unit {
        val localVarResponse = refundFailedPostWithHttpInfo(webhookRefundPayload = webhookRefundPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Refund Failed
     * Occurs when a payment refund fails.
     * @param webhookRefundPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun refundFailedPostWithHttpInfo(webhookRefundPayload: WebhookRefundPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = refundFailedPostRequestConfig(webhookRefundPayload = webhookRefundPayload)

        return request<WebhookRefundPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation refundFailedPost
     *
     * @param webhookRefundPayload  (optional)
     * @return RequestConfig
     */
    fun refundFailedPostRequestConfig(webhookRefundPayload: WebhookRefundPayload?) : RequestConfig<WebhookRefundPayload> {
        val localVariableBody = webhookRefundPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/refund.failed",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Refund Succeeded
     * Occurs when a payment refund is confirmed as succeeded.
     * @param webhookRefundPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun refundSucceededPost(webhookRefundPayload: WebhookRefundPayload? = null) : Unit {
        val localVarResponse = refundSucceededPostWithHttpInfo(webhookRefundPayload = webhookRefundPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Refund Succeeded
     * Occurs when a payment refund is confirmed as succeeded.
     * @param webhookRefundPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun refundSucceededPostWithHttpInfo(webhookRefundPayload: WebhookRefundPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = refundSucceededPostRequestConfig(webhookRefundPayload = webhookRefundPayload)

        return request<WebhookRefundPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation refundSucceededPost
     *
     * @param webhookRefundPayload  (optional)
     * @return RequestConfig
     */
    fun refundSucceededPostRequestConfig(webhookRefundPayload: WebhookRefundPayload?) : RequestConfig<WebhookRefundPayload> {
        val localVariableBody = webhookRefundPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/refund.succeeded",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Subscription Created
     * Occurs when a customer subscription is successfully started.
     * @param webhookSubscriptionPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionCreatedPost(webhookSubscriptionPayload: WebhookSubscriptionPayload? = null) : Unit {
        val localVarResponse = subscriptionCreatedPostWithHttpInfo(webhookSubscriptionPayload = webhookSubscriptionPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Subscription Created
     * Occurs when a customer subscription is successfully started.
     * @param webhookSubscriptionPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionCreatedPostWithHttpInfo(webhookSubscriptionPayload: WebhookSubscriptionPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = subscriptionCreatedPostRequestConfig(webhookSubscriptionPayload = webhookSubscriptionPayload)

        return request<WebhookSubscriptionPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionCreatedPost
     *
     * @param webhookSubscriptionPayload  (optional)
     * @return RequestConfig
     */
    fun subscriptionCreatedPostRequestConfig(webhookSubscriptionPayload: WebhookSubscriptionPayload?) : RequestConfig<WebhookSubscriptionPayload> {
        val localVariableBody = webhookSubscriptionPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/subscription.created",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Subscription Deactivated
     * Occurs when a customer subscription is deactivated or expired.
     * @param webhookSubscriptionPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionDeactivatedPost(webhookSubscriptionPayload: WebhookSubscriptionPayload? = null) : Unit {
        val localVarResponse = subscriptionDeactivatedPostWithHttpInfo(webhookSubscriptionPayload = webhookSubscriptionPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Subscription Deactivated
     * Occurs when a customer subscription is deactivated or expired.
     * @param webhookSubscriptionPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionDeactivatedPostWithHttpInfo(webhookSubscriptionPayload: WebhookSubscriptionPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = subscriptionDeactivatedPostRequestConfig(webhookSubscriptionPayload = webhookSubscriptionPayload)

        return request<WebhookSubscriptionPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionDeactivatedPost
     *
     * @param webhookSubscriptionPayload  (optional)
     * @return RequestConfig
     */
    fun subscriptionDeactivatedPostRequestConfig(webhookSubscriptionPayload: WebhookSubscriptionPayload?) : RequestConfig<WebhookSubscriptionPayload> {
        val localVariableBody = webhookSubscriptionPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/subscription.deactivated",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Subscription Updated
     * Occurs when a customer subscription is updated (e.g., cancel at period end changes).
     * @param webhookSubscriptionPayload  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionUpdatedPost(webhookSubscriptionPayload: WebhookSubscriptionPayload? = null) : Unit {
        val localVarResponse = subscriptionUpdatedPostWithHttpInfo(webhookSubscriptionPayload = webhookSubscriptionPayload)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Subscription Updated
     * Occurs when a customer subscription is updated (e.g., cancel at period end changes).
     * @param webhookSubscriptionPayload  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionUpdatedPostWithHttpInfo(webhookSubscriptionPayload: WebhookSubscriptionPayload?) : ApiResponse<Unit?> {
        val localVariableConfig = subscriptionUpdatedPostRequestConfig(webhookSubscriptionPayload = webhookSubscriptionPayload)

        return request<WebhookSubscriptionPayload, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionUpdatedPost
     *
     * @param webhookSubscriptionPayload  (optional)
     * @return RequestConfig
     */
    fun subscriptionUpdatedPostRequestConfig(webhookSubscriptionPayload: WebhookSubscriptionPayload?) : RequestConfig<WebhookSubscriptionPayload> {
        val localVariableBody = webhookSubscriptionPayload
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        
        return RequestConfig(
            method = RequestMethod.POST,
            path = "/subscription.updated",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
