/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.solifyn.model.Dispute
import com.solifyn.model.DisputeEvidenceUpdate
import com.solifyn.model.DisputeFileUpload
import com.solifyn.model.DisputeList

import com.squareup.moshi.Json

import com.solifyn.infrastructure.ApiClient
import com.solifyn.infrastructure.ApiResponse
import com.solifyn.infrastructure.ClientException
import com.solifyn.infrastructure.ClientError
import com.solifyn.infrastructure.ServerException
import com.solifyn.infrastructure.ServerError
import com.solifyn.infrastructure.MultiValueMap
import com.solifyn.infrastructure.PartConfig
import com.solifyn.infrastructure.RequestConfig
import com.solifyn.infrastructure.RequestMethod
import com.solifyn.infrastructure.ResponseType
import com.solifyn.infrastructure.Success
import com.solifyn.infrastructure.toMultiValue

class DisputesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8000")
        }
    }

    /**
     * Generate Dispute CSV Report
     * Generates a downloadable CSV report of disputes matching the filters.
     * @param createdAtGte Filter disputes created after this ISO date-time string (optional)
     * @param createdAtLte Filter disputes created before this ISO date-time string (optional)
     * @param status Filter disputes by status (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputesGenerateReport(createdAtGte: kotlin.String? = null, createdAtLte: kotlin.String? = null, status: kotlin.String? = null) : Unit {
        val localVarResponse = disputesGenerateReportWithHttpInfo(createdAtGte = createdAtGte, createdAtLte = createdAtLte, status = status)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Generate Dispute CSV Report
     * Generates a downloadable CSV report of disputes matching the filters.
     * @param createdAtGte Filter disputes created after this ISO date-time string (optional)
     * @param createdAtLte Filter disputes created before this ISO date-time string (optional)
     * @param status Filter disputes by status (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun disputesGenerateReportWithHttpInfo(createdAtGte: kotlin.String?, createdAtLte: kotlin.String?, status: kotlin.String?) : ApiResponse<Unit?> {
        val localVariableConfig = disputesGenerateReportRequestConfig(createdAtGte = createdAtGte, createdAtLte = createdAtLte, status = status)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputesGenerateReport
     *
     * @param createdAtGte Filter disputes created after this ISO date-time string (optional)
     * @param createdAtLte Filter disputes created before this ISO date-time string (optional)
     * @param status Filter disputes by status (optional)
     * @return RequestConfig
     */
    fun disputesGenerateReportRequestConfig(createdAtGte: kotlin.String?, createdAtLte: kotlin.String?, status: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (createdAtGte != null) {
                    put("createdAtGte", listOf(createdAtGte.toString()))
                }
                if (createdAtLte != null) {
                    put("createdAtLte", listOf(createdAtLte.toString()))
                }
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        
        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/transactions/disputes/report",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Retrieve Dispute
     * Retrieve details of a specific dispute by ID.
     * @param id The dispute ID
     * @return Dispute
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputesGet(id: kotlin.String) : Dispute {
        val localVarResponse = disputesGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Dispute
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieve Dispute
     * Retrieve details of a specific dispute by ID.
     * @param id The dispute ID
     * @return ApiResponse<Dispute?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun disputesGetWithHttpInfo(id: kotlin.String) : ApiResponse<Dispute?> {
        val localVariableConfig = disputesGetRequestConfig(id = id)

        return request<Unit, Dispute>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputesGet
     *
     * @param id The dispute ID
     * @return RequestConfig
     */
    fun disputesGetRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/transactions/disputes/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List Disputes
     * Retrieve disputes associated with the active business.
     * @param page Page number for pagination (optional)
     * @param limit Page size limit for pagination (optional)
     * @param status Filter disputes by status (optional)
     * @param type Filter by type: dispute or alert (optional)
     * @return DisputeList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputesList(page: kotlin.String? = null, limit: kotlin.String? = null, status: kotlin.String? = null, type: kotlin.String? = null) : DisputeList {
        val localVarResponse = disputesListWithHttpInfo(page = page, limit = limit, status = status, type = type)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DisputeList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List Disputes
     * Retrieve disputes associated with the active business.
     * @param page Page number for pagination (optional)
     * @param limit Page size limit for pagination (optional)
     * @param status Filter disputes by status (optional)
     * @param type Filter by type: dispute or alert (optional)
     * @return ApiResponse<DisputeList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun disputesListWithHttpInfo(page: kotlin.String?, limit: kotlin.String?, status: kotlin.String?, type: kotlin.String?) : ApiResponse<DisputeList?> {
        val localVariableConfig = disputesListRequestConfig(page = page, limit = limit, status = status, type = type)

        return request<Unit, DisputeList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputesList
     *
     * @param page Page number for pagination (optional)
     * @param limit Page size limit for pagination (optional)
     * @param status Filter disputes by status (optional)
     * @param type Filter by type: dispute or alert (optional)
     * @return RequestConfig
     */
    fun disputesListRequestConfig(page: kotlin.String?, limit: kotlin.String?, status: kotlin.String?, type: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (status != null) {
                    put("status", listOf(status.toString()))
                }
                if (type != null) {
                    put("type", listOf(type.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/transactions/disputes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Submit Dispute Evidence
     * Finalize and submit the uploaded evidence for review.
     * @param id The dispute ID
     * @return Dispute
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputesSubmitEvidence(id: kotlin.String) : Dispute {
        val localVarResponse = disputesSubmitEvidenceWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Dispute
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Submit Dispute Evidence
     * Finalize and submit the uploaded evidence for review.
     * @param id The dispute ID
     * @return ApiResponse<Dispute?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun disputesSubmitEvidenceWithHttpInfo(id: kotlin.String) : ApiResponse<Dispute?> {
        val localVariableConfig = disputesSubmitEvidenceRequestConfig(id = id)

        return request<Unit, Dispute>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputesSubmitEvidence
     *
     * @param id The dispute ID
     * @return RequestConfig
     */
    fun disputesSubmitEvidenceRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/transactions/disputes/{id}/submit".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Update Dispute Evidence
     * Upload and update evidence attachments for a dispute.
     * @param id The dispute ID
     * @param disputeEvidenceUpdate 
     * @return Dispute
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputesUpdateEvidence(id: kotlin.String, disputeEvidenceUpdate: DisputeEvidenceUpdate) : Dispute {
        val localVarResponse = disputesUpdateEvidenceWithHttpInfo(id = id, disputeEvidenceUpdate = disputeEvidenceUpdate)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Dispute
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Update Dispute Evidence
     * Upload and update evidence attachments for a dispute.
     * @param id The dispute ID
     * @param disputeEvidenceUpdate 
     * @return ApiResponse<Dispute?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun disputesUpdateEvidenceWithHttpInfo(id: kotlin.String, disputeEvidenceUpdate: DisputeEvidenceUpdate) : ApiResponse<Dispute?> {
        val localVariableConfig = disputesUpdateEvidenceRequestConfig(id = id, disputeEvidenceUpdate = disputeEvidenceUpdate)

        return request<DisputeEvidenceUpdate, Dispute>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputesUpdateEvidence
     *
     * @param id The dispute ID
     * @param disputeEvidenceUpdate 
     * @return RequestConfig
     */
    fun disputesUpdateEvidenceRequestConfig(id: kotlin.String, disputeEvidenceUpdate: DisputeEvidenceUpdate) : RequestConfig<DisputeEvidenceUpdate> {
        val localVariableBody = disputeEvidenceUpdate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/transactions/disputes/{id}/evidence".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Upload Evidence File
     * Upload a support file (image, PDF, video) to use as dispute evidence.
     * @param file The evidence file to upload (Max 25MB: JPEG, PNG, GIF, WEBP, PDF, MP4, WEBM, QuickTime)
     * @return DisputeFileUpload
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun disputesUploadEvidenceFile(file: java.io.File) : DisputeFileUpload {
        val localVarResponse = disputesUploadEvidenceFileWithHttpInfo(file = file)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DisputeFileUpload
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Upload Evidence File
     * Upload a support file (image, PDF, video) to use as dispute evidence.
     * @param file The evidence file to upload (Max 25MB: JPEG, PNG, GIF, WEBP, PDF, MP4, WEBM, QuickTime)
     * @return ApiResponse<DisputeFileUpload?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun disputesUploadEvidenceFileWithHttpInfo(file: java.io.File) : ApiResponse<DisputeFileUpload?> {
        val localVariableConfig = disputesUploadEvidenceFileRequestConfig(file = file)

        return request<Map<String, PartConfig<*>>, DisputeFileUpload>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation disputesUploadEvidenceFile
     *
     * @param file The evidence file to upload (Max 25MB: JPEG, PNG, GIF, WEBP, PDF, MP4, WEBM, QuickTime)
     * @return RequestConfig
     */
    fun disputesUploadEvidenceFileRequestConfig(file: java.io.File) : RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = mapOf(
            "file" to PartConfig(body = file, headers = mutableMapOf()),)
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "multipart/form-data")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/transactions/disputes/upload",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
