/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.solifyn.model.PayoutAccessToken
import com.solifyn.model.PayoutAccount
import com.solifyn.model.PayoutAccountLink
import com.solifyn.model.PayoutMethodList
import com.solifyn.model.PayoutVerificationList
import com.solifyn.model.Withdrawal
import com.solifyn.model.WithdrawalCreate
import com.solifyn.model.WithdrawalList

import com.squareup.moshi.Json

import com.solifyn.infrastructure.ApiClient
import com.solifyn.infrastructure.ApiResponse
import com.solifyn.infrastructure.ClientException
import com.solifyn.infrastructure.ClientError
import com.solifyn.infrastructure.ServerException
import com.solifyn.infrastructure.ServerError
import com.solifyn.infrastructure.MultiValueMap
import com.solifyn.infrastructure.PartConfig
import com.solifyn.infrastructure.RequestConfig
import com.solifyn.infrastructure.RequestMethod
import com.solifyn.infrastructure.ResponseType
import com.solifyn.infrastructure.Success
import com.solifyn.infrastructure.toMultiValue

class PayoutsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8000")
        }
    }

    /**
     * Create Withdrawal
     * Initiate a balance withdrawal transfer request.
     * @param withdrawalCreate 
     * @return Withdrawal
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsCreateWithdrawal(withdrawalCreate: WithdrawalCreate) : Withdrawal {
        val localVarResponse = payoutsCreateWithdrawalWithHttpInfo(withdrawalCreate = withdrawalCreate)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as Withdrawal
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Create Withdrawal
     * Initiate a balance withdrawal transfer request.
     * @param withdrawalCreate 
     * @return ApiResponse<Withdrawal?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsCreateWithdrawalWithHttpInfo(withdrawalCreate: WithdrawalCreate) : ApiResponse<Withdrawal?> {
        val localVariableConfig = payoutsCreateWithdrawalRequestConfig(withdrawalCreate = withdrawalCreate)

        return request<WithdrawalCreate, Withdrawal>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsCreateWithdrawal
     *
     * @param withdrawalCreate 
     * @return RequestConfig
     */
    fun payoutsCreateWithdrawalRequestConfig(withdrawalCreate: WithdrawalCreate) : RequestConfig<WithdrawalCreate> {
        val localVariableBody = withdrawalCreate
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/payouts/withdrawals",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Retrieve Payout Account
     * Retrieve general status and information of onboarding payout accounts.
     * @return PayoutAccount
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsGetAccount() : PayoutAccount {
        val localVarResponse = payoutsGetAccountWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PayoutAccount
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieve Payout Account
     * Retrieve general status and information of onboarding payout accounts.
     * @return ApiResponse<PayoutAccount?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsGetAccountWithHttpInfo() : ApiResponse<PayoutAccount?> {
        val localVariableConfig = payoutsGetAccountRequestConfig()

        return request<Unit, PayoutAccount>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsGetAccount
     *
     * @return RequestConfig
     */
    fun payoutsGetAccountRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/payouts/account",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * enum for parameter useCase
     */
     enum class UseCasePayoutsGetAccountLink(val value: kotlin.String) {
         @Json(name = "account_onboarding") account_onboarding("account_onboarding"),
         @Json(name = "payouts_portal") payouts_portal("payouts_portal");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * Create Account Link
     * Generate temporary links for onboarding or viewing portals.
     * @param useCase Onboarding link type context (optional)
     * @return PayoutAccountLink
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsGetAccountLink(useCase: UseCasePayoutsGetAccountLink? = null) : PayoutAccountLink {
        val localVarResponse = payoutsGetAccountLinkWithHttpInfo(useCase = useCase)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PayoutAccountLink
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Create Account Link
     * Generate temporary links for onboarding or viewing portals.
     * @param useCase Onboarding link type context (optional)
     * @return ApiResponse<PayoutAccountLink?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsGetAccountLinkWithHttpInfo(useCase: UseCasePayoutsGetAccountLink?) : ApiResponse<PayoutAccountLink?> {
        val localVariableConfig = payoutsGetAccountLinkRequestConfig(useCase = useCase)

        return request<Unit, PayoutAccountLink>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsGetAccountLink
     *
     * @param useCase Onboarding link type context (optional)
     * @return RequestConfig
     */
    fun payoutsGetAccountLinkRequestConfig(useCase: UseCasePayoutsGetAccountLink?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (useCase != null) {
                    put("use_case", listOf(useCase.value))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/payouts/account-link",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Generate Portal Access Token
     * Generate temporary credentials to access the embed portal.
     * @return PayoutAccessToken
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsGetToken() : PayoutAccessToken {
        val localVarResponse = payoutsGetTokenWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PayoutAccessToken
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Generate Portal Access Token
     * Generate temporary credentials to access the embed portal.
     * @return ApiResponse<PayoutAccessToken?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsGetTokenWithHttpInfo() : ApiResponse<PayoutAccessToken?> {
        val localVariableConfig = payoutsGetTokenRequestConfig()

        return request<Unit, PayoutAccessToken>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsGetToken
     *
     * @return RequestConfig
     */
    fun payoutsGetTokenRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/payouts/token",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Get Withdrawals List
     * Retrieve withdrawal records for the active business.
     * @param limit Page size limit (optional)
     * @param page Page number (optional)
     * @return WithdrawalList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsGetWithdrawals(limit: java.math.BigDecimal? = null, page: java.math.BigDecimal? = null) : WithdrawalList {
        val localVarResponse = payoutsGetWithdrawalsWithHttpInfo(limit = limit, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WithdrawalList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Get Withdrawals List
     * Retrieve withdrawal records for the active business.
     * @param limit Page size limit (optional)
     * @param page Page number (optional)
     * @return ApiResponse<WithdrawalList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsGetWithdrawalsWithHttpInfo(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : ApiResponse<WithdrawalList?> {
        val localVariableConfig = payoutsGetWithdrawalsRequestConfig(limit = limit, page = page)

        return request<Unit, WithdrawalList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsGetWithdrawals
     *
     * @param limit Page size limit (optional)
     * @param page Page number (optional)
     * @return RequestConfig
     */
    fun payoutsGetWithdrawalsRequestConfig(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/payouts/withdrawals",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List Payout Methods
     * List saved payout destinations (bank accounts, cards).
     * @param limit  (optional)
     * @param page  (optional)
     * @return PayoutMethodList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsListMethods(limit: java.math.BigDecimal? = null, page: java.math.BigDecimal? = null) : PayoutMethodList {
        val localVarResponse = payoutsListMethodsWithHttpInfo(limit = limit, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PayoutMethodList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List Payout Methods
     * List saved payout destinations (bank accounts, cards).
     * @param limit  (optional)
     * @param page  (optional)
     * @return ApiResponse<PayoutMethodList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsListMethodsWithHttpInfo(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : ApiResponse<PayoutMethodList?> {
        val localVariableConfig = payoutsListMethodsRequestConfig(limit = limit, page = page)

        return request<Unit, PayoutMethodList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsListMethods
     *
     * @param limit  (optional)
     * @param page  (optional)
     * @return RequestConfig
     */
    fun payoutsListMethodsRequestConfig(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/payouts/methods",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List Verifications
     * Retrieve pending or completed KYC verification checks.
     * @param limit  (optional)
     * @param page  (optional)
     * @return PayoutVerificationList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsListVerifications(limit: java.math.BigDecimal? = null, page: java.math.BigDecimal? = null) : PayoutVerificationList {
        val localVarResponse = payoutsListVerificationsWithHttpInfo(limit = limit, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PayoutVerificationList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List Verifications
     * Retrieve pending or completed KYC verification checks.
     * @param limit  (optional)
     * @param page  (optional)
     * @return ApiResponse<PayoutVerificationList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsListVerificationsWithHttpInfo(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : ApiResponse<PayoutVerificationList?> {
        val localVariableConfig = payoutsListVerificationsRequestConfig(limit = limit, page = page)

        return request<Unit, PayoutVerificationList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsListVerifications
     *
     * @param limit  (optional)
     * @param page  (optional)
     * @return RequestConfig
     */
    fun payoutsListVerificationsRequestConfig(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/payouts/verifications",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List Withdrawals
     * Retrieve a list of past withdrawal history.
     * @param limit Page size limit (optional)
     * @param page Page number (optional)
     * @return WithdrawalList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun payoutsListWithdrawals(limit: java.math.BigDecimal? = null, page: java.math.BigDecimal? = null) : WithdrawalList {
        val localVarResponse = payoutsListWithdrawalsWithHttpInfo(limit = limit, page = page)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as WithdrawalList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List Withdrawals
     * Retrieve a list of past withdrawal history.
     * @param limit Page size limit (optional)
     * @param page Page number (optional)
     * @return ApiResponse<WithdrawalList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun payoutsListWithdrawalsWithHttpInfo(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : ApiResponse<WithdrawalList?> {
        val localVariableConfig = payoutsListWithdrawalsRequestConfig(limit = limit, page = page)

        return request<Unit, WithdrawalList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation payoutsListWithdrawals
     *
     * @param limit Page size limit (optional)
     * @param page Page number (optional)
     * @return RequestConfig
     */
    fun payoutsListWithdrawalsRequestConfig(limit: java.math.BigDecimal?, page: java.math.BigDecimal?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/payouts",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
