/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.api

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.solifyn.model.SubscriptionAction
import com.solifyn.model.SubscriptionDetail
import com.solifyn.model.SubscriptionList
import com.solifyn.model.SubscriptionsAction201Response

import com.squareup.moshi.Json

import com.solifyn.infrastructure.ApiClient
import com.solifyn.infrastructure.ApiResponse
import com.solifyn.infrastructure.ClientException
import com.solifyn.infrastructure.ClientError
import com.solifyn.infrastructure.ServerException
import com.solifyn.infrastructure.ServerError
import com.solifyn.infrastructure.MultiValueMap
import com.solifyn.infrastructure.PartConfig
import com.solifyn.infrastructure.RequestConfig
import com.solifyn.infrastructure.RequestMethod
import com.solifyn.infrastructure.ResponseType
import com.solifyn.infrastructure.Success
import com.solifyn.infrastructure.toMultiValue

class SubscriptionsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost:8000")
        }
    }

    /**
     * enum for parameter action
     */
     enum class ActionSubscriptionsAction(val value: kotlin.String) {
         @Json(name = "add_free_days") add_free_days("add_free_days"),
         @Json(name = "cancel") cancel("cancel"),
         @Json(name = "pause") pause("pause"),
         @Json(name = "resume") resume("resume"),
         @Json(name = "uncancel") uncancel("uncancel"),
         @Json(name = "adjust_seats") adjust_seats("adjust_seats");

        /**
         * Override [toString()] to avoid using the enum variable name as the value, and instead use
         * the actual value defined in the API spec file.
         *
         * This solves a problem when the variable name and its value are different, and ensures that
         * the client sends the correct enum values to the server always.
         */
        override fun toString(): kotlin.String = "$value"
     }

    /**
     * Subscription Action
     * Cancel, pause, resume, or add free days to a customer subscription.
     * @param subscriptionId The customer subscription ID
     * @param action The subscription task to execute
     * @param subscriptionAction 
     * @return SubscriptionsAction201Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionsAction(subscriptionId: kotlin.String, action: ActionSubscriptionsAction, subscriptionAction: SubscriptionAction) : SubscriptionsAction201Response {
        val localVarResponse = subscriptionsActionWithHttpInfo(subscriptionId = subscriptionId, action = action, subscriptionAction = subscriptionAction)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SubscriptionsAction201Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Subscription Action
     * Cancel, pause, resume, or add free days to a customer subscription.
     * @param subscriptionId The customer subscription ID
     * @param action The subscription task to execute
     * @param subscriptionAction 
     * @return ApiResponse<SubscriptionsAction201Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionsActionWithHttpInfo(subscriptionId: kotlin.String, action: ActionSubscriptionsAction, subscriptionAction: SubscriptionAction) : ApiResponse<SubscriptionsAction201Response?> {
        val localVariableConfig = subscriptionsActionRequestConfig(subscriptionId = subscriptionId, action = action, subscriptionAction = subscriptionAction)

        return request<SubscriptionAction, SubscriptionsAction201Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionsAction
     *
     * @param subscriptionId The customer subscription ID
     * @param action The subscription task to execute
     * @param subscriptionAction 
     * @return RequestConfig
     */
    fun subscriptionsActionRequestConfig(subscriptionId: kotlin.String, action: ActionSubscriptionsAction, subscriptionAction: SubscriptionAction) : RequestConfig<SubscriptionAction> {
        val localVariableBody = subscriptionAction
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/subscriptions/{subscriptionId}/{action}".replace("{"+"subscriptionId"+"}", encodeURIComponent(subscriptionId.toString())).replace("{"+"action"+"}", encodeURIComponent(action.value.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * Retrieve Subscription Details
     * Retrieve detailed information about a subscription and its billing history.
     * @param id The customer subscription ID
     * @return SubscriptionDetail
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionsGet(id: kotlin.String) : SubscriptionDetail {
        val localVarResponse = subscriptionsGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SubscriptionDetail
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * Retrieve Subscription Details
     * Retrieve detailed information about a subscription and its billing history.
     * @param id The customer subscription ID
     * @return ApiResponse<SubscriptionDetail?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionsGetWithHttpInfo(id: kotlin.String) : ApiResponse<SubscriptionDetail?> {
        val localVariableConfig = subscriptionsGetRequestConfig(id = id)

        return request<Unit, SubscriptionDetail>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionsGet
     *
     * @param id The customer subscription ID
     * @return RequestConfig
     */
    fun subscriptionsGetRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/subscriptions/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * List Subscriptions
     * Retrieve a list of customer subscriptions, optionally filtered by customer ID.
     * @param customerId Filter subscriptions by customer ID. (optional)
     * @return SubscriptionList
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun subscriptionsList(customerId: kotlin.String? = null) : SubscriptionList {
        val localVarResponse = subscriptionsListWithHttpInfo(customerId = customerId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SubscriptionList
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * List Subscriptions
     * Retrieve a list of customer subscriptions, optionally filtered by customer ID.
     * @param customerId Filter subscriptions by customer ID. (optional)
     * @return ApiResponse<SubscriptionList?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun subscriptionsListWithHttpInfo(customerId: kotlin.String?) : ApiResponse<SubscriptionList?> {
        val localVariableConfig = subscriptionsListRequestConfig(customerId = customerId)

        return request<Unit, SubscriptionList>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation subscriptionsList
     *
     * @param customerId Filter subscriptions by customer ID. (optional)
     * @return RequestConfig
     */
    fun subscriptionsListRequestConfig(customerId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (customerId != null) {
                    put("customerId", listOf(customerId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/subscriptions",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
