/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.AddonUpdate

class AddonUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AddonUpdate
        //val modelInstance = AddonUpdate()

        // to test the property `minQuantity` - Minimum quantity of the addon allowed to be purchased.
        should("test minQuantity") {
            // uncomment below to test the property
            //modelInstance.minQuantity shouldBe ("TODO")
        }

        // to test the property `maxQuantity` - Maximum quantity of the addon allowed to be purchased (optional).
        should("test maxQuantity") {
            // uncomment below to test the property
            //modelInstance.maxQuantity shouldBe ("TODO")
        }

        // to test the property `priceOverride` - Price override for the addon product when purchased with this parent (optional).
        should("test priceOverride") {
            // uncomment below to test the property
            //modelInstance.priceOverride shouldBe ("TODO")
        }

        // to test the property `isSeatAddon` - Flag indicating if this addon represents a seat/license limit increment.
        should("test isSeatAddon") {
            // uncomment below to test the property
            //modelInstance.isSeatAddon shouldBe ("TODO")
        }

    }
}
