/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.ApiKeyResponseDto

class ApiKeyResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ApiKeyResponseDto
        //val modelInstance = ApiKeyResponseDto()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `prefix`
        should("test prefix") {
            // uncomment below to test the property
            //modelInstance.prefix shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `allowWrite`
        should("test allowWrite") {
            // uncomment below to test the property
            //modelInstance.allowWrite shouldBe ("TODO")
        }

        // to test the property `expiresAt`
        should("test expiresAt") {
            // uncomment below to test the property
            //modelInstance.expiresAt shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `apiKey` - The raw API key. Only returned once during creation.
        should("test apiKey") {
            // uncomment below to test the property
            //modelInstance.apiKey shouldBe ("TODO")
        }

        // to test the property `lastUsedAt`
        should("test lastUsedAt") {
            // uncomment below to test the property
            //modelInstance.lastUsedAt shouldBe ("TODO")
        }

    }
}
