/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.Business

class BusinessTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Business
        //val modelInstance = Business()

        // to test the property `id` - The unique business ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title` - Title or name of the business
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `whopId` - The Whop Company ID
        should("test whopId") {
            // uncomment below to test the property
            //modelInstance.whopId shouldBe ("TODO")
        }

        // to test the property `merchantId` - The merchant owner ID
        should("test merchantId") {
            // uncomment below to test the property
            //modelInstance.merchantId shouldBe ("TODO")
        }

        // to test the property `verified` - Whether the business has been KYC-verified on Whop
        should("test verified") {
            // uncomment below to test the property
            //modelInstance.verified shouldBe ("TODO")
        }

        // to test the property `sendCustomerEmails` - Whether auto-emails are enabled for customers
        should("test sendCustomerEmails") {
            // uncomment below to test the property
            //modelInstance.sendCustomerEmails shouldBe ("TODO")
        }

        // to test the property `memberCount` - Total members/customers under this business
        should("test memberCount") {
            // uncomment below to test the property
            //modelInstance.memberCount shouldBe ("TODO")
        }

        // to test the property `defaultCurrency` - The default currency of the business
        should("test defaultCurrency") {
            // uncomment below to test the property
            //modelInstance.defaultCurrency shouldBe ("TODO")
        }

        // to test the property `publishedReviewsCount` - Number of published user reviews on Whop
        should("test publishedReviewsCount") {
            // uncomment below to test the property
            //modelInstance.publishedReviewsCount shouldBe ("TODO")
        }

        // to test the property `createdAt` - Timestamp when the business record was created
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Timestamp when the business record was last updated
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `description` - A description explaining what the business does
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `route` - Whop friendly URL path route
        should("test route") {
            // uncomment below to test the property
            //modelInstance.route shouldBe ("TODO")
        }

        // to test the property `metadata` - Custom key-value metadata
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `targetAudience` - The target audience description
        should("test targetAudience") {
            // uncomment below to test the property
            //modelInstance.targetAudience shouldBe ("TODO")
        }

        // to test the property `socialLinks` - Social links setup
        should("test socialLinks") {
            // uncomment below to test the property
            //modelInstance.socialLinks shouldBe ("TODO")
        }

        // to test the property `affiliateInstructions` - Markdown instructions for affiliates
        should("test affiliateInstructions") {
            // uncomment below to test the property
            //modelInstance.affiliateInstructions shouldBe ("TODO")
        }

        // to test the property `whopCreatedAt` - Whop account creation timestamp
        should("test whopCreatedAt") {
            // uncomment below to test the property
            //modelInstance.whopCreatedAt shouldBe ("TODO")
        }

        // to test the property `whopUpdatedAt` - Whop account last updated timestamp
        should("test whopUpdatedAt") {
            // uncomment below to test the property
            //modelInstance.whopUpdatedAt shouldBe ("TODO")
        }

        // to test the property `logoUrl` - Brand logo image URL resolved from primary brand
        should("test logoUrl") {
            // uncomment below to test the property
            //modelInstance.logoUrl shouldBe ("TODO")
        }

    }
}
