/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.CollectionProductEntry

class CollectionProductEntryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CollectionProductEntry
        //val modelInstance = CollectionProductEntry()

        // to test the property `id` - The product ID (whopId or internal database ID)
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `quantity` - Quantity of this product in the collection. Required, defaults to 1.
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

    }
}
