/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.CollectionProductDto

class CollectionProductDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CollectionProductDto
        //val modelInstance = CollectionProductDto()

        // to test the property `id` - The unique identifier (ID) of the product.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - The display name of the product.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `price` - The price amount of the product (e.g. 29.00).
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `currency` - The three-letter ISO currency code (e.g. USD, VND, EUR).
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `status` - The lifecycle status of the product (e.g. ACTIVE, ARCHIVED).
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `imageUrl` - URL of the product cover image.
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `taxCategory` - The tax classification for the product.
        should("test taxCategory") {
            // uncomment below to test the property
            //modelInstance.taxCategory shouldBe ("TODO")
        }

        // to test the property `pricingType` - Pricing model of the product.
        should("test pricingType") {
            // uncomment below to test the property
            //modelInstance.pricingType shouldBe ("TODO")
        }

        // to test the property `discount` - Discount value as a percentage or fixed amount.
        should("test discount") {
            // uncomment below to test the property
            //modelInstance.discount shouldBe ("TODO")
        }

        // to test the property `hasLicenseKey` - Indicates if the product issues a cryptographically secure software license key upon checkout completion.
        should("test hasLicenseKey") {
            // uncomment below to test the property
            //modelInstance.hasLicenseKey shouldBe ("TODO")
        }

        // to test the property `hasDigitalDelivery` - Whether the product includes digital file downloads upon purchase.
        should("test hasDigitalDelivery") {
            // uncomment below to test the property
            //modelInstance.hasDigitalDelivery shouldBe ("TODO")
        }

        // to test the property `hasGithubAccess` - Whether the product includes GitHub repository access.
        should("test hasGithubAccess") {
            // uncomment below to test the property
            //modelInstance.hasGithubAccess shouldBe ("TODO")
        }

        // to test the property `githubRepo` - GitHub repository to grant access to (format: owner/repo).
        should("test githubRepo") {
            // uncomment below to test the property
            //modelInstance.githubRepo shouldBe ("TODO")
        }

        // to test the property `githubPermission` - GitHub collaborator permission level.
        should("test githubPermission") {
            // uncomment below to test the property
            //modelInstance.githubPermission shouldBe ("TODO")
        }

        // to test the property `isTaxInclusive` - Whether the product price already includes applicable sales taxes.
        should("test isTaxInclusive") {
            // uncomment below to test the property
            //modelInstance.isTaxInclusive shouldBe ("TODO")
        }

        // to test the property `billingPeriod` - The subscription billing cycle interval in days (for subscription products).
        should("test billingPeriod") {
            // uncomment below to test the property
            //modelInstance.billingPeriod shouldBe ("TODO")
        }

        // to test the property `trialPeriodDays` - Trial duration in days for subscription products.
        should("test trialPeriodDays") {
            // uncomment below to test the property
            //modelInstance.trialPeriodDays shouldBe ("TODO")
        }

        // to test the property `expirationDays` - Automatic expiration period in days for the subscription entitlement.
        should("test expirationDays") {
            // uncomment below to test the property
            //modelInstance.expirationDays shouldBe ("TODO")
        }

        // to test the property `statementDescriptor` - Custom text displayed on customer credit card statements for purchases of this product.
        should("test statementDescriptor") {
            // uncomment below to test the property
            //modelInstance.statementDescriptor shouldBe ("TODO")
        }

        // to test the property `payWhatYouWant` - Indicates if customers are allowed to enter a custom pricing amount at checkout.
        should("test payWhatYouWant") {
            // uncomment below to test the property
            //modelInstance.payWhatYouWant shouldBe ("TODO")
        }

        // to test the property `metadata` - Custom developer metadata key-value pairs associated with the product.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `customFields` - Custom form field questions to ask the customer during checkout.
        should("test customFields") {
            // uncomment below to test the property
            //modelInstance.customFields shouldBe ("TODO")
        }

        // to test the property `stock` - Available stock quantity, or null for unlimited inventory.
        should("test stock") {
            // uncomment below to test the property
            //modelInstance.stock shouldBe ("TODO")
        }

        // to test the property `activationLimit` - Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true).
        should("test activationLimit") {
            // uncomment below to test the property
            //modelInstance.activationLimit shouldBe ("TODO")
        }

        // to test the property `isListed` - Defines if the product is listed publicly on the merchant's storefront template.
        should("test isListed") {
            // uncomment below to test the property
            //modelInstance.isListed shouldBe ("TODO")
        }

        // to test the property `isFree` - Whether the product is free.
        should("test isFree") {
            // uncomment below to test the property
            //modelInstance.isFree shouldBe ("TODO")
        }

        // to test the property `createdAt` - Timestamp indicating exactly when the product was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Timestamp indicating when the product was last modified.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `isPermanentlyDeleted` - Indicates if the product has been permanently deleted.
        should("test isPermanentlyDeleted") {
            // uncomment below to test the property
            //modelInstance.isPermanentlyDeleted shouldBe ("TODO")
        }

        // to test the property `brandId` - Optional brand identifier.
        should("test brandId") {
            // uncomment below to test the property
            //modelInstance.brandId shouldBe ("TODO")
        }

        // to test the property `digitalLink` - Secure link for digital delivery.
        should("test digitalLink") {
            // uncomment below to test the property
            //modelInstance.digitalLink shouldBe ("TODO")
        }

        // to test the property `instructions` - Special instructions provided upon purchase.
        should("test instructions") {
            // uncomment below to test the property
            //modelInstance.instructions shouldBe ("TODO")
        }

        // to test the property `activationMessage` - Custom message displayed when a license key is activated.
        should("test activationMessage") {
            // uncomment below to test the property
            //modelInstance.activationMessage shouldBe ("TODO")
        }

        // to test the property `expiryHours` - Number of hours until the license key expires.
        should("test expiryHours") {
            // uncomment below to test the property
            //modelInstance.expiryHours shouldBe ("TODO")
        }

        // to test the property `businessId` - The unique identifier of the business owning this product.
        should("test businessId") {
            // uncomment below to test the property
            //modelInstance.businessId shouldBe ("TODO")
        }

        // to test the property `quantity` - Quantity of the product in the collection
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

        // to test the property `description` - A comprehensive rich text description of the product.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
