/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.CollectionProductRefDto

class CollectionProductRefDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CollectionProductRefDto
        //val modelInstance = CollectionProductRefDto()

        // to test the property `id` - The public product identifier (whopId or internal ID)
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `quantity` - Quantity of this product in the collection
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

    }
}
