/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.CollectionArchivedResponseDto

class CollectionArchivedResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CollectionArchivedResponseDto
        //val modelInstance = CollectionArchivedResponseDto()

        // to test the property `message` - Response message indicating the outcome of the action.
        should("test message") {
            // uncomment below to test the property
            //modelInstance.message shouldBe ("TODO")
        }

    }
}
