/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.CreateSetupCheckoutDto

class CreateSetupCheckoutDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateSetupCheckoutDto
        //val modelInstance = CreateSetupCheckoutDto()

        // to test the property `companyId` - The Whop/Stripe company ID context
        should("test companyId") {
            // uncomment below to test the property
            //modelInstance.companyId shouldBe ("TODO")
        }

        // to test the property `currency` - Currency for setup mode
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `retryPaymentId` - Internal or Whop failed payment ID to retry
        should("test retryPaymentId") {
            // uncomment below to test the property
            //modelInstance.retryPaymentId shouldBe ("TODO")
        }

        // to test the property `membershipId` - Membership ID to link setup checkout to for card updating
        should("test membershipId") {
            // uncomment below to test the property
            //modelInstance.membershipId shouldBe ("TODO")
        }

        // to test the property `planId` - Plan ID to retry or renew
        should("test planId") {
            // uncomment below to test the property
            //modelInstance.planId shouldBe ("TODO")
        }

    }
}
