/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.DashboardStatsDto

class DashboardStatsDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DashboardStatsDto
        //val modelInstance = DashboardStatsDto()

        // to test the property `revenue` - Gross revenue in cents
        should("test revenue") {
            // uncomment below to test the property
            //modelInstance.revenue shouldBe ("TODO")
        }

        // to test the property `ordersCount` - Total payments processed count
        should("test ordersCount") {
            // uncomment below to test the property
            //modelInstance.ordersCount shouldBe ("TODO")
        }

        // to test the property `refundsCount` - Gross amount refunded in cents
        should("test refundsCount") {
            // uncomment below to test the property
            //modelInstance.refundsCount shouldBe ("TODO")
        }

        // to test the property `activeMemberships` - Number of active paying customers/memberships
        should("test activeMemberships") {
            // uncomment below to test the property
            //modelInstance.activeMemberships shouldBe ("TODO")
        }

    }
}
