/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.DisputeEvidenceUpdate
import com.solifyn.model.DisputeAttachmentDto

class DisputeEvidenceUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DisputeEvidenceUpdate
        //val modelInstance = DisputeEvidenceUpdate()

        // to test the property `cancellationPolicyAttachment` - Evidence showing cancellation policy details
        should("test cancellationPolicyAttachment") {
            // uncomment below to test the property
            //modelInstance.cancellationPolicyAttachment shouldBe ("TODO")
        }

        // to test the property `customerCommunicationAttachment` - Evidence demonstrating communications with the customer
        should("test customerCommunicationAttachment") {
            // uncomment below to test the property
            //modelInstance.customerCommunicationAttachment shouldBe ("TODO")
        }

        // to test the property `refundPolicyAttachment` - Evidence showing refund policy details
        should("test refundPolicyAttachment") {
            // uncomment below to test the property
            //modelInstance.refundPolicyAttachment shouldBe ("TODO")
        }

        // to test the property `uncategorizedAttachment` - Uncategorized supporting files or documents
        should("test uncategorizedAttachment") {
            // uncomment below to test the property
            //modelInstance.uncategorizedAttachment shouldBe ("TODO")
        }

    }
}
