/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.DisputeFileUpload

class DisputeFileUploadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DisputeFileUpload
        //val modelInstance = DisputeFileUpload()

        // to test the property `id` - Uploaded file ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `filename` - Name of the file
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

        // to test the property `uploadUrl` - S3 presigned upload URL
        should("test uploadUrl") {
            // uncomment below to test the property
            //modelInstance.uploadUrl shouldBe ("TODO")
        }

        // to test the property `uploadHeaders` - HTTP headers required for the S3 upload request
        should("test uploadHeaders") {
            // uncomment below to test the property
            //modelInstance.uploadHeaders shouldBe ("TODO")
        }

    }
}
