/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.DisputeListMetaDto

class DisputeListMetaDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DisputeListMetaDto
        //val modelInstance = DisputeListMetaDto()

        // to test the property `total` - Total count of disputes
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `page` - Current page number
        should("test page") {
            // uncomment below to test the property
            //modelInstance.page shouldBe ("TODO")
        }

        // to test the property `limit` - Limit of items per page
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `totalPages` - Total number of pages
        should("test totalPages") {
            // uncomment below to test the property
            //modelInstance.totalPages shouldBe ("TODO")
        }

    }
}
