/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.EntitlementDetailResponseDto
import com.solifyn.model.LinkedProductDto

class EntitlementDetailResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntitlementDetailResponseDto
        //val modelInstance = EntitlementDetailResponseDto()

        // to test the property `id` - The unique entitlement ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `businessId` - The owning business ID
        should("test businessId") {
            // uncomment below to test the property
            //modelInstance.businessId shouldBe ("TODO")
        }

        // to test the property `name` - The name of the entitlement
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type` - The type of access to grant
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `status` - Status of the entitlement
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `createdAt` - When the entitlement was created
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - When the entitlement was last updated
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `grantsCount` - Number of active customer grants issued from this entitlement
        should("test grantsCount") {
            // uncomment below to test the property
            //modelInstance.grantsCount shouldBe ("TODO")
        }

        // to test the property `products` - Products that are currently linked to this entitlement
        should("test products") {
            // uncomment below to test the property
            //modelInstance.products shouldBe ("TODO")
        }

        // to test the property `githubRepo` - The GitHub repository (e.g., owner/repo)
        should("test githubRepo") {
            // uncomment below to test the property
            //modelInstance.githubRepo shouldBe ("TODO")
        }

        // to test the property `githubPermission` - The GitHub repository permission level
        should("test githubPermission") {
            // uncomment below to test the property
            //modelInstance.githubPermission shouldBe ("TODO")
        }

        // to test the property `discordGuildId` - The Discord Guild/Server ID
        should("test discordGuildId") {
            // uncomment below to test the property
            //modelInstance.discordGuildId shouldBe ("TODO")
        }

        // to test the property `discordRoleId` - The Discord Role ID to assign
        should("test discordRoleId") {
            // uncomment below to test the property
            //modelInstance.discordRoleId shouldBe ("TODO")
        }

        // to test the property `framerTemplateId` - The associated Framer Template ID
        should("test framerTemplateId") {
            // uncomment below to test the property
            //modelInstance.framerTemplateId shouldBe ("TODO")
        }

        // to test the property `licenseKey` - The static License Key (if not dynamically generated)
        should("test licenseKey") {
            // uncomment below to test the property
            //modelInstance.licenseKey shouldBe ("TODO")
        }

        // to test the property `activationLimit` - The maximum activation limit for licenses
        should("test activationLimit") {
            // uncomment below to test the property
            //modelInstance.activationLimit shouldBe ("TODO")
        }

        // to test the property `activationMessage` - A message shown to the user upon license activation
        should("test activationMessage") {
            // uncomment below to test the property
            //modelInstance.activationMessage shouldBe ("TODO")
        }

        // to test the property `expiryHours` - The number of hours until the entitlement expires
        should("test expiryHours") {
            // uncomment below to test the property
            //modelInstance.expiryHours shouldBe ("TODO")
        }

        // to test the property `digitalLink` - The digital download URL or redirect link
        should("test digitalLink") {
            // uncomment below to test the property
            //modelInstance.digitalLink shouldBe ("TODO")
        }

        // to test the property `instructions` - Custom setup instructions for the user
        should("test instructions") {
            // uncomment below to test the property
            //modelInstance.instructions shouldBe ("TODO")
        }

    }
}
