/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.Instance

class InstanceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Instance
        //val modelInstance = Instance()

        // to test the property `id` - The unique database identifier of this instance record.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `licenseId` - The internal ID of the parent license key this instance belongs to.
        should("test licenseId") {
            // uncomment below to test the property
            //modelInstance.licenseId shouldBe ("TODO")
        }

        // to test the property `instanceId` - The unique hardware hash or client-generated identifier of the activated device/machine.
        should("test instanceId") {
            // uncomment below to test the property
            //modelInstance.instanceId shouldBe ("TODO")
        }

        // to test the property `instanceName` - A human-readable display name for this instance, assigned by the client application.
        should("test instanceName") {
            // uncomment below to test the property
            //modelInstance.instanceName shouldBe ("TODO")
        }

        // to test the property `ipAddress` - The IP address recorded at the time of activation.
        should("test ipAddress") {
            // uncomment below to test the property
            //modelInstance.ipAddress shouldBe ("TODO")
        }

        // to test the property `activatedAt` - Timestamp when this device instance was first activated.
        should("test activatedAt") {
            // uncomment below to test the property
            //modelInstance.activatedAt shouldBe ("TODO")
        }

        // to test the property `lastSeenAt` - Timestamp of the most recent activation heartbeat or re-activation check from this device.
        should("test lastSeenAt") {
            // uncomment below to test the property
            //modelInstance.lastSeenAt shouldBe ("TODO")
        }

    }
}
