/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.LicensesDeactivateRequest

class LicensesDeactivateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LicensesDeactivateRequest
        //val modelInstance = LicensesDeactivateRequest()

        // to test the property `key` - The license key.
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

    }
}
