/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.LicensesActivateRequest

class LicensesActivateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LicensesActivateRequest
        //val modelInstance = LicensesActivateRequest()

        // to test the property `key` - The license key.
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `deviceIdentifier` - Unique identifier of the device/machine being activated.
        should("test deviceIdentifier") {
            // uncomment below to test the property
            //modelInstance.deviceIdentifier shouldBe ("TODO")
        }

        // to test the property `name` - A user-friendly label/name for the instance.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
