/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.LicensesDeactivate200Response

class LicensesDeactivate200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LicensesDeactivate200Response
        //val modelInstance = LicensesDeactivate200Response()

        // to test the property `success`
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

    }
}
