/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.MeterEventsResponseDto
import com.solifyn.model.MeterUsageEventDto

class MeterEventsResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MeterEventsResponseDto
        //val modelInstance = MeterEventsResponseDto()

        // to test the property `meterId` - The unique meter ID.
        should("test meterId") {
            // uncomment below to test the property
            //modelInstance.meterId shouldBe ("TODO")
        }

        // to test the property `items` - List of recent usage events.
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `count` - Number of returned usage events.
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

    }
}
