/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.MeterUsageEventDto

class MeterUsageEventDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MeterUsageEventDto
        //val modelInstance = MeterUsageEventDto()

        // to test the property `id` - The unique usage event ID.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `meterId` - The meter ID this event belongs to.
        should("test meterId") {
            // uncomment below to test the property
            //modelInstance.meterId shouldBe ("TODO")
        }

        // to test the property `customerId` - The customer ID associated with the usage event.
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property ``value`` - Numeric usage value recorded for the event.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `timestamp` - Timestamp when the usage event occurred.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `processedAt` - Timestamp when the usage event was processed.
        should("test processedAt") {
            // uncomment below to test the property
            //modelInstance.processedAt shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional event metadata.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
