/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.OperationalWebhookEndpointSecretInDto

class OperationalWebhookEndpointSecretInDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OperationalWebhookEndpointSecretInDto
        //val modelInstance = OperationalWebhookEndpointSecretInDto()

        // to test the property `key` - Optional custom endpoint signing secret (base64 encoded random bytes optionally prefixed with whsec_). If not set, a new random secret is generated.
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

    }
}
