/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.OperationalWebhookEndpointInDto

class OperationalWebhookEndpointInDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OperationalWebhookEndpointInDto
        //val modelInstance = OperationalWebhookEndpointInDto()

        // to test the property `url` - The URL to send webhook events to.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `description` - Optional description for the endpoint.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `disabled` - Whether the endpoint is disabled.
        should("test disabled") {
            // uncomment below to test the property
            //modelInstance.disabled shouldBe ("TODO")
        }

        // to test the property `filterTypes` - The operational event types this endpoint will receive.
        should("test filterTypes") {
            // uncomment below to test the property
            //modelInstance.filterTypes shouldBe ("TODO")
        }

        // to test the property `metadata` - Metadata key-value pairs associated with the endpoint.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `secret` - Optional custom endpoint signing secret (base64 encoded random bytes optionally prefixed with whsec_). If not set, the server will generate one.
        should("test secret") {
            // uncomment below to test the property
            //modelInstance.secret shouldBe ("TODO")
        }

        // to test the property `throttleRate` - Maximum messages per second to send to this endpoint (outgoing messages will be throttled to this rate).
        should("test throttleRate") {
            // uncomment below to test the property
            //modelInstance.throttleRate shouldBe ("TODO")
        }

        // to test the property `uid` - Optional unique user-defined identifier for the endpoint.
        should("test uid") {
            // uncomment below to test the property
            //modelInstance.uid shouldBe ("TODO")
        }

    }
}
