/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.OperationalWebhookEndpointHeadersResponseDto

class OperationalWebhookEndpointHeadersResponseDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OperationalWebhookEndpointHeadersResponseDto
        //val modelInstance = OperationalWebhookEndpointHeadersResponseDto()

        // to test the property `headers` - Key-value headers sent with the webhook.
        should("test headers") {
            // uncomment below to test the property
            //modelInstance.headers shouldBe ("TODO")
        }

        // to test the property `sensitive` - List of sensitive header keys (e.g. Authorization) that are masked.
        should("test sensitive") {
            // uncomment below to test the property
            //modelInstance.sensitive shouldBe ("TODO")
        }

    }
}
