/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.OrderRefundCreate
import com.solifyn.model.RevokeSeatDto

class OrderRefundCreateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderRefundCreate
        //val modelInstance = OrderRefundCreate()

        // to test the property `amount` - The refund amount in cents. If full refund is true, this can represent the total amount.
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `isFullRefund` - Whether this is a full refund or a partial refund.
        should("test isFullRefund") {
            // uncomment below to test the property
            //modelInstance.isFullRefund shouldBe ("TODO")
        }

        // to test the property `idempotencyKey` - A unique idempotency key to prevent double refunds for transient network retries.
        should("test idempotencyKey") {
            // uncomment below to test the property
            //modelInstance.idempotencyKey shouldBe ("TODO")
        }

        // to test the property `autoRevokeSeats` - Whether to automatically revoke seat add-ons matching the refund amount.
        should("test autoRevokeSeats") {
            // uncomment below to test the property
            //modelInstance.autoRevokeSeats shouldBe ("TODO")
        }

        // to test the property `revokeSeats` - List of specific addons and the quantities of seats to revoke.
        should("test revokeSeats") {
            // uncomment below to test the property
            //modelInstance.revokeSeats shouldBe ("TODO")
        }

    }
}
