/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.OrderBillingUpdate

class OrderBillingUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderBillingUpdate
        //val modelInstance = OrderBillingUpdate()

        // to test the property `street`
        should("test street") {
            // uncomment below to test the property
            //modelInstance.street shouldBe ("TODO")
        }

        // to test the property `city`
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `zipcode`
        should("test zipcode") {
            // uncomment below to test the property
            //modelInstance.zipcode shouldBe ("TODO")
        }

        // to test the property `country`
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

    }
}
