/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.Order
import com.solifyn.model.OrderBilling
import com.solifyn.model.OrderCustomer
import com.solifyn.model.OrderDetail
import com.solifyn.model.OrderProductCart
import com.solifyn.model.OrderRefund

class OrderTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Order
        //val modelInstance = Order()

        // to test the property `id` - Unique internal database identifier.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `invoiceUrl` - The invoice print URL.
        should("test invoiceUrl") {
            // uncomment below to test the property
            //modelInstance.invoiceUrl shouldBe ("TODO")
        }

        // to test the property `customer` - Customer details.
        should("test customer") {
            // uncomment below to test the property
            //modelInstance.customer shouldBe ("TODO")
        }

        // to test the property `totalAmount` - Total paid amount in cents.
        should("test totalAmount") {
            // uncomment below to test the property
            //modelInstance.totalAmount shouldBe ("TODO")
        }

        // to test the property `subtotal` - Subtotal amount in cents.
        should("test subtotal") {
            // uncomment below to test the property
            //modelInstance.subtotal shouldBe ("TODO")
        }

        // to test the property `taxAmount` - Tax amount in cents.
        should("test taxAmount") {
            // uncomment below to test the property
            //modelInstance.taxAmount shouldBe ("TODO")
        }

        // to test the property `applicationFee` - Application fee in cents.
        should("test applicationFee") {
            // uncomment below to test the property
            //modelInstance.applicationFee shouldBe ("TODO")
        }

        // to test the property `amountAfterFees` - Net amount after fees in cents.
        should("test amountAfterFees") {
            // uncomment below to test the property
            //modelInstance.amountAfterFees shouldBe ("TODO")
        }

        // to test the property `currency` - Currency code.
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `status` - Current status of the payment.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `createdAt` - Payment creation timestamp.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `paymentMethod` - Payment method utilized.
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `productCart` - Products purchased in this order.
        should("test productCart") {
            // uncomment below to test the property
            //modelInstance.productCart shouldBe ("TODO")
        }

        // to test the property `refundable` - Indicates whether the order is eligible for refund.
        should("test refundable") {
            // uncomment below to test the property
            //modelInstance.refundable shouldBe ("TODO")
        }

        // to test the property `businessId` - Business unique ID identifier.
        should("test businessId") {
            // uncomment below to test the property
            //modelInstance.businessId shouldBe ("TODO")
        }

        // to test the property `businessName` - Business display title/name.
        should("test businessName") {
            // uncomment below to test the property
            //modelInstance.businessName shouldBe ("TODO")
        }

        // to test the property `paidAt` - Payment completion/paid timestamp.
        should("test paidAt") {
            // uncomment below to test the property
            //modelInstance.paidAt shouldBe ("TODO")
        }

        // to test the property `cardLastFour` - Last four digits of card used.
        should("test cardLastFour") {
            // uncomment below to test the property
            //modelInstance.cardLastFour shouldBe ("TODO")
        }

        // to test the property `cardNetwork` - Card network/brand.
        should("test cardNetwork") {
            // uncomment below to test the property
            //modelInstance.cardNetwork shouldBe ("TODO")
        }

        // to test the property `cardType` - Card type.
        should("test cardType") {
            // uncomment below to test the property
            //modelInstance.cardType shouldBe ("TODO")
        }

        // to test the property `billing` - Billing address details.
        should("test billing") {
            // uncomment below to test the property
            //modelInstance.billing shouldBe ("TODO")
        }

        // to test the property `metadata` - Custom metadata payload associated with this payment.
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `order` - Order details snapshot.
        should("test order") {
            // uncomment below to test the property
            //modelInstance.order shouldBe ("TODO")
        }

        // to test the property `refunds` - List of refunds associated with this payment.
        should("test refunds") {
            // uncomment below to test the property
            //modelInstance.refunds shouldBe ("TODO")
        }

        // to test the property `billingReason` - Billing reason detail.
        should("test billingReason") {
            // uncomment below to test the property
            //modelInstance.billingReason shouldBe ("TODO")
        }

    }
}
