/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.PayoutMethod

class PayoutMethodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayoutMethod
        //val modelInstance = PayoutMethod()

        // to test the property `id` - The payout method ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type` - Type of payout method (e.g. bank_account, stripe)
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `status` - Status of the payout method
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `details` - Metadata and details of the bank/card associated
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

    }
}
