/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.ProductCreateAddonsInner

class ProductCreateAddonsInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProductCreateAddonsInner
        //val modelInstance = ProductCreateAddonsInner()

        // to test the property `productId`
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `minQuantity`
        should("test minQuantity") {
            // uncomment below to test the property
            //modelInstance.minQuantity shouldBe ("TODO")
        }

        // to test the property `maxQuantity`
        should("test maxQuantity") {
            // uncomment below to test the property
            //modelInstance.maxQuantity shouldBe ("TODO")
        }

        // to test the property `priceOverride`
        should("test priceOverride") {
            // uncomment below to test the property
            //modelInstance.priceOverride shouldBe ("TODO")
        }

        // to test the property `isSeatAddon`
        should("test isSeatAddon") {
            // uncomment below to test the property
            //modelInstance.isSeatAddon shouldBe ("TODO")
        }

    }
}
