/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.ResolvedAddon

class ResolvedAddonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResolvedAddon
        //val modelInstance = ResolvedAddon()

        // to test the property `productId` - Unique product ID of the addon
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `name` - Display name of the addon
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `imageUrl` - URL of the addon image
        should("test imageUrl") {
            // uncomment below to test the property
            //modelInstance.imageUrl shouldBe ("TODO")
        }

        // to test the property `quantity` - The purchased quantity of the addon
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

    }
}
