/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.SubscriptionDetailProduct

class SubscriptionDetailProductTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubscriptionDetailProduct
        //val modelInstance = SubscriptionDetailProduct()

        // to test the property `id` - The product unique ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - The product name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `price` - Product base price
        should("test price") {
            // uncomment below to test the property
            //modelInstance.price shouldBe ("TODO")
        }

        // to test the property `currency` - Base currency
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `pricingType` - Pricing type, e.g. one-time or renewal
        should("test pricingType") {
            // uncomment below to test the property
            //modelInstance.pricingType shouldBe ("TODO")
        }

        // to test the property `metadata` - Metadata JSON payload
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
