/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.UpdateCollectionProductDto

class UpdateCollectionProductDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateCollectionProductDto
        //val modelInstance = UpdateCollectionProductDto()

        // to test the property `quantity` - New quantity of this product in the collection.
        should("test quantity") {
            // uncomment below to test the property
            //modelInstance.quantity shouldBe ("TODO")
        }

    }
}
