/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.UserTheme

class UserThemeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserTheme
        //val modelInstance = UserTheme()

        // to test the property `id` - Theme configuration ID
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `config` - Styling config JSON (fontFamily, borderRadius, colors)
        should("test config") {
            // uncomment below to test the property
            //modelInstance.config shouldBe ("TODO")
        }

        // to test the property `businessId` - The linked business ID
        should("test businessId") {
            // uncomment below to test the property
            //modelInstance.businessId shouldBe ("TODO")
        }

        // to test the property `avatarUrl` - Logo/avatar image URL
        should("test avatarUrl") {
            // uncomment below to test the property
            //modelInstance.avatarUrl shouldBe ("TODO")
        }

        // to test the property `bannerUrl` - Header banner image URL
        should("test bannerUrl") {
            // uncomment below to test the property
            //modelInstance.bannerUrl shouldBe ("TODO")
        }

    }
}
