/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.WebhookSubscriptionPayload

class WebhookSubscriptionPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebhookSubscriptionPayload
        //val modelInstance = WebhookSubscriptionPayload()

        // to test the property `id` - The subscription ID.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `status` - Current status of the subscription.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `cancelAtPeriodEnd`
        should("test cancelAtPeriodEnd") {
            // uncomment below to test the property
            //modelInstance.cancelAtPeriodEnd shouldBe ("TODO")
        }

        // to test the property `renewalPeriodStart`
        should("test renewalPeriodStart") {
            // uncomment below to test the property
            //modelInstance.renewalPeriodStart shouldBe ("TODO")
        }

        // to test the property `renewalPeriodEnd`
        should("test renewalPeriodEnd") {
            // uncomment below to test the property
            //modelInstance.renewalPeriodEnd shouldBe ("TODO")
        }

        // to test the property `currency`
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `amount`
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `customerId`
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `customerEmail`
        should("test customerEmail") {
            // uncomment below to test the property
            //modelInstance.customerEmail shouldBe ("TODO")
        }

        // to test the property `customerName`
        should("test customerName") {
            // uncomment below to test the property
            //modelInstance.customerName shouldBe ("TODO")
        }

        // to test the property `productId`
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `productTitle`
        should("test productTitle") {
            // uncomment below to test the property
            //modelInstance.productTitle shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
