/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.solifyn.model

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.solifyn.model.WebhookEntitlementGrantPayload

class WebhookEntitlementGrantPayloadTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WebhookEntitlementGrantPayload
        //val modelInstance = WebhookEntitlementGrantPayload()

        // to test the property `id` - The unique entitlement grant ID.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `businessId` - The business ID context.
        should("test businessId") {
            // uncomment below to test the property
            //modelInstance.businessId shouldBe ("TODO")
        }

        // to test the property `customerId` - The customer ID.
        should("test customerId") {
            // uncomment below to test the property
            //modelInstance.customerId shouldBe ("TODO")
        }

        // to test the property `paymentId` - Associated payment transaction ID.
        should("test paymentId") {
            // uncomment below to test the property
            //modelInstance.paymentId shouldBe ("TODO")
        }

        // to test the property `productId` - The purchased product ID.
        should("test productId") {
            // uncomment below to test the property
            //modelInstance.productId shouldBe ("TODO")
        }

        // to test the property `type` - The type of entitlement (e.g. GITHUB).
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `githubRepo` - Target GitHub repository (owner/repo) if type is GITHUB.
        should("test githubRepo") {
            // uncomment below to test the property
            //modelInstance.githubRepo shouldBe ("TODO")
        }

        // to test the property `githubPermission` - GitHub access permission level if type is GITHUB.
        should("test githubPermission") {
            // uncomment below to test the property
            //modelInstance.githubPermission shouldBe ("TODO")
        }

        // to test the property `githubUsername` - The connected customer GitHub username.
        should("test githubUsername") {
            // uncomment below to test the property
            //modelInstance.githubUsername shouldBe ("TODO")
        }

        // to test the property `status` - Delivery status of the collaborator invite (PENDING, DELIVERED, FAILED, REVOKED).
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `oauthUrl` - OAuth URL to redirect the customer to.
        should("test oauthUrl") {
            // uncomment below to test the property
            //modelInstance.oauthUrl shouldBe ("TODO")
        }

        // to test the property `errorDetails` - Error message if invitation delivery failed.
        should("test errorDetails") {
            // uncomment below to test the property
            //modelInstance.errorDetails shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
